---
title: "Introduction to Neurolinguistics"
author: "Likan Zhan"
date: '2019-09-01'
lastmod: "`r Sys.Date()`"
show_toc: yes
disable_comments: yes
output:
  blogdown::html_page:
    toc: yes
---

# 1. Time and Location

- Time: 10:10 - 12:00, Each Monday

- Location: Room 514, Teaching Building one

- Lecturer: Likan Zhan

# 2. Course Information

This class intends to provide a coherent view on the relation between language and the brain based on the multifold empirical data coming from different research fields: electrophysiological and functional neuroimaging data of the adult language system, neuroscientific data of the developmental language system, and data on the brain structure and its maturation in humans as well as in non-human primates.

# 3. TextBook

- Friederici, A. D. (2017). *Language in Our Brain: The Origins of a Uniquely Human Capacity*. Cambridge, MA: The MIT Press.

<!---
- Ahlsen, E. (2006). *Introduction to Neurolinguistics*. Amsterdam, The Netherlands: John Benjamins Publishing.
- Ingram, J. C. L. (2007). *Neurolinguistics: An Introduction to Spoken Language Processing and its Disorders*. Cambridge, UK: Cambridge University Press.
- Kemmerer, D. (2014). *Cognitive Neuroscience of Language*. New York, NY: Psychology Press.
- Schnelle, H. (2010). *Language in the Brain*. Cambridge, UK: Cambridge University Press.
--->

# 4. Syllabus and Lecture Notes

- Part 0. Introduction
  - Chapter.00. Introduction to the Course: [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](https://likan.oss-cn-beijing.aliyuncs.com/NeuroLing/CH_00.pdf)

- Part I. The brain regions affording Language: [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](https://likan.oss-cn-beijing.aliyuncs.com/NeuroLing/CH_01_0_0.pdf)
  - Chapter 1. Language Functions in the Brain: [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](https://likan.oss-cn-beijing.aliyuncs.com/NeuroLing/CH_01_0_1.pdf)
    - Section 1.1. A Cognitive Model of Auditory Language Comprehension: [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](https://likan.oss-cn-beijing.aliyuncs.com/NeuroLing/CH_01_1.pdf)
    - Section 1.2. Acoustic-Phonological Processes: [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](https://likan.oss-cn-beijing.aliyuncs.com/NeuroLing/CH_01_2.pdf)
    - Section 1.3. From Word Form to Syntactic and Lexical-Semantic Information: [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](https://likan.oss-cn-beijing.aliyuncs.com/NeuroLing/CH_01_3.pdf)
    - Section 1.4. Initial Phrase Structure Building: [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](https://likan.oss-cn-beijing.aliyuncs.com/NeuroLing/CH_01_4.pdf)
    - Section 1.5. Syntactic Relations during Sentence Processing: [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](https://likan.oss-cn-beijing.aliyuncs.com/NeuroLing/CH_01_5.pdf)
    - Section 1.6. Processing Semantic Relations: [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](https://likan.oss-cn-beijing.aliyuncs.com/NeuroLing/CH_01_6.pdf)
    - Section 1.7. Thematic Role Assignment: Semantic and Syntactic Features
    - Section 1.8. Processing Prosodic Information
    - Section 1.9. Functional Neuroanatomy of Language Comprehension

  - Chapter 2. Excursions

- Part II. The brain networks affording Language
  - Chapter 3. The Structural Language Network
  - Chapter 4. The Functional Language Network

- Part III. The brain basis of language acquisition
  - Chapter 5. The Brain’s Critical Period for Language Acquisition
  - Chapter 6. Ontogeny of the Neural Language Network

- Part IV. The evolution of language
  - Chapter 7. Evolution of Language
  - Chapter 8. The Neural Basis of Language

# 5. Examination

To Be Announced

<!---
- Your will write a reading report of an academic article.
- The article you read should
  - be written in English;
  - be an appropriate article for the course, i.e., relating to neurolinguistics;
  - be published in the last five years, i.e., 2015 - 2019;
  - be an original research article, not a review article;
- The report you submitted should
  - be written in Chinese;
  - be about 3000 words in length (Chinese Charaters);
  - consist of two main parts:
    - background, methods, and main findings of the article ( about 1500 - 2000 words);
    - future directions of this topic (1000 - 1500 words).
- Your should send your report to my email address before **January 11, 2020, 23:59**.
--->