baseurl = "https://likan.info/"
languageCode = "en-us"
title = "Zhan, Likan | 战立侃"
theme = "hugo-ivy"
googleAnalytics = "UA-112592341-1"
disqusShortname = "https-likanzhan-github-io"
ignoreFiles = ["\\.Rmd$", "_cache$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage = true  # .WordCount works correctly for chinese
enableEmoji = true
footnotereturnlinkcontents = "↩"
MetaDataFormat = "yaml" # format of a new post
enableGitInfo = false
disablePathToLower = true

[[menu.main]]
    name = "English"
    url = "/en/"
    weight = 1

[[menu.main]]
    name = "中文"
    url = "/cn/"
    weight = 2

[[menu.main]]
    name = "小组"
    url = "https://sapere-aude.group"
    weight = 3

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2

[[menu.en]]
    name = "CV"
    url = "/en/cv/likan_zhan_cv_en/"
    weight = 3

[[menu.en]]
    name = "Team"
    url = "https://sapere-aude.group"
    weight = 7

[[menu.en]]
    name = "中文"
    url = "/cn/"
    weight = 70

[[menu.cn]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2

[[menu.cn]]
    name = "简历"
    url = "/cn/cv/likan_zhan_cv_cn/"
    weight = 3


[[menu.cn]]
    name = "小组"
    url = "https://sapere-aude.group"
    weight = 8

[[menu.cn]]
    name = "English"
    url = "/en/"
    weight = 80

[params]
    description        = "Personal website of Likan Zhan"
    disqusURL          = "https://likan.info"
    githubContentURL   = "https://github.com/rbind/likan/edit/master/content/"
    highlightjsVersion = "9.12.0"
    highlightjsLang    = ["r", "yaml", "tex"]
    highlightjsTheme   = "github"
    dateFormat         = "2006-01-02" # "2006-01-02, Mon, "

[params.accounts]
    email          = "zhanlikan@hotmail.com"
    github         = "https://github.com/likanzhan"
    google_scholar = "https://scholar.google.com/citations?user=QvyaktcAAAAJ&hl=en"
    academia       = "https://blcu.academia.edu/likanzhan"
    orcid          = "https://orcid.org/0000-0002-9275-3557"
    publons        = "https://publons.com/researcher/1149653/likan-zhan"
    researchgate   = "https://www.researchgate.net/profile/Likan_Zhan"
    stack_overflow  = "https://stackoverflow.com/users/2263930"
    osf            = "https://osf.io/j8wrg"

[params.footer]
    en = "Powered by [Hugo](https://gohugo.io) and [Blogdown](https://bookdown.org/yihui/blogdown/)  &copy; [Likan Zhan](/) 2017 - 2023"
    cn = "本站由 [Hugo](https://gohugo.io) 和 [Blogdown](https://bookdown.org/yihui/blogdown/) 强力驱动 &copy; [战立侃](/)      2017 - 2023"

[params.author]
    en = "Likan Zhan"
    cn = "战立侃"

[params.logo.en]
    img = "/assets/logo/bodhi.png"
    url = "/"
    alt = "Likan Zhan"
    tag = ""

[params.lang.edit]
    cn = "编辑"
[params.lang.license]
    cn = "版权"
[params.lang.subscribe]
    cn = "订阅"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
