---
title: Useful Webs
author: "Likan Zhan"
date: '2019-11-02'
lastmod: "`r Sys.Date()`"
disable_comments: false
output:
  blogdown::html_page:
    toc: true
---

# Personal website or official webpage

9. [Yi Xu](http://www.homepages.ucl.ac.uk/~uclyyix/), Professor of Speech Sciences, University College London, London, UK.

> My research is primarily concerned with the basic mechanisms of speech production and perception in connected discourse, especially in terms of how multiple layers of communicative meanings can be encoded through a common process of articulation. In particular, I am interested in the production, perception, typology, and modelling and synthesis of speech prosody, as well as the basic mechanisms of coarticulation. I am also concerned with computational modeling of the neural process of speech acquisition. More recently, I have developed an interest in the understanding of emotional expressions in speech from an evolutionary perspective.

8. [Tecumseh Fitch](https://homepage.univie.ac.at/tecumseh.fitch/), Professor of Cognitive Biology, University of Vienna, Austria.

> Tecumseh Fitch is an evolutionary biologist and cognitive scientist. He is Professor of Cognitive Biology at the University of Vienna. Prof. Fitch’s interests include bioacoustics and biolinguistics, specifically the evolution of speech, language and music.

7. [Dale Barr](https://www.gla.ac.uk/researchinstitutes/neurosciencepsychology/staff/dalebarr/), Institute of Neuroscience & Psychology, University of Glasgow, UK

> Ph.D. from University of Chicago. Interested in the psychology of communication and conversation, as well as in statistical methodology. 

6. [Yi Ting Huang](https://hesp.umd.edu/facultyprofile/huang/yi-ting), Associate Professor, Department of Hearing and Speech Sciences, University of Maryland, MD.

> Yi Ting Huang is an Associate Professor in the Department of Hearing and Speech Sciences. She received her Ph.D. in Developmental Psychology at Harvard University and trained as a post-doctoral fellow in Cognitive Psychology at the University of North Carolina at Chapel Hill. Dr. Huang’s research focuses on how young language learners acquire the ability to coordinate linguistic representations during real-time comprehension. She explores this question by using eye-tracking methods to examine how the moment-to-moment changes that occur during processing influence the year-to-year changes that emerge during development. She has applied this approach to examine a variety of topics including word recognition, application of grammatical knowledge, and the generation of pragmatic inferences. Other interests include the relationship between language and concepts, language comprehension and production, and language development and literacy.  She is currently a member of the Maryland Language Science Center and the Program in Neuroscience and Cognitive Science.

5. [Cecilia Heyes](http://users.ox.ac.uk/~ascch/index.htm), Senior Research Fellow in Theoretical Life Sciences, University of Oxford, UK.

> My work concerns the evolution of cognition. It explores the ways in which natural selection, learning, developmental and cultural processes combine to produce the mature cognitive abilities found in adult humans. I am especially interested in social cognition. Most of my current projects examine the possibility that the neurocognitive mechanisms enabling cultural inheritance - social learning, imitation, mirror neurons, mind reading etc - are themselves products of cultural evolution.

4. [Uta Frith](https://sites.google.com/site/utafrith/), Emeritus Professor of Cognitive Development, Institute of Cognitive Neuroscience, UCL.

> I have been Emeritus Professor of Cognitive Development at UCL Institute of Cognitive Neuroscience since 2006. I have been a Visiting Professor at the University of Aarhus at the Interacting Minds Centre from 2007 to 2015. I have been a Fellow at the Institute for Advanced Studies at the Central European University in Budapest (February - June 2014). From 1998 to 2008 I was Deputy Director of the UCL Institute of Cognitive Neuroscience, and before this I was a member of two MRC Units affiliated to UCL, The MRC Developmental Psychology Unit (1968-1982) and the MRC Cognitive Development Unit (1982-1998).  What am I doing? Some of my time is now spent trying to write a book with Chris Frith on "What makes us social". We want to draw together what is known about evolution, development and pathology of social cognition. But we are also working towards a graphic novel with the same content. Our son, Alex Frith is supervising this project as author and director; Daniel Locke is the artist. We also post random pieces of this and that on our frithmind blog.  I am still as fascinated as ever with autism and with dyslexia. in 2014 I enjoyed making the BBC2 Horizon programme "Living with autism".  This gave me a taste for being more active in science communication. In 2015 I presented a BBC2 Horizon documentary on OCD "A monster in my mind";  in 2017 a documentary on "What makes a psychopath".  You can probably catch these programmes on YouTube. 

3. [Matthew Traxler](https://psychology.ucdavis.edu/people/traxler), Professor of Psychology, Center for Mind and Brain, University of California at Davis, Davis, CA

> Professor Traxler’s primary research interests center on the (largely) unconscious processes that underlie language comprehension. He is currently the primary investigator on an NIH-sponsored project that investigates the link between working memory capacity and the cognitive processes involves in syntactic parsing. Other recent research has investigated the semantic processing that occurs when default interpretations fail and the types of memory representations that facilitate processing of newly introduced concepts. 

2. [Keith Johnson](http://linguistics.berkeley.edu/~kjohnson/index.html), Department of linguistics, University of California at Berkeley, Berkeley, CA.

> I am a linguist and a phonetician at the university of california at berkeley. my affiliation at uc.berkeley is with the department of linguistics and i serve as the director of the uc.berkeley phonetics and phonology lab (the Phonlab).

1. [Steven Sloman](https://sites.google.com/site/slomanlab/lab-members), Professor of cognitive, linguistic, and psychological sciences, Brown University,

> Steve did his PhD in Psychology at Stanford University from 1986-1990 and then did post-doctoral research for two years at the University of Michigan. He is currently Editor-in-Chief of the journal Cognition. Steven is a cognitive scientist who studies how people think. He has studied how our habits of thought influence the way we see the world, how the different systems that constitute thought interact to produce conclusions, conflict, and conversation, and how our construal of how the world works influences how we evaluate events and decide what actions to take.

# Research groups and Laboratories

7. [the dynamics of cognition and communication](https://www.thedocc.com), lead by [Zheng (Joyce) Wang](https://www.thedocc.com/wp-content/uploads/2018/10/WangCV.pdf), at The Ohio State University, Columbus, OH.

> Our Communication and Psychophysiology Lab (CAP Lab) focuses on understanding “the dynamics of cognition and communication” (the DOCC), especially: Motivation, emotion, and cognition in media processing and choice behavior; media design and evaluation. Reciprocal dynamics of choice behavior and information processing; mHealth (mobile health) applications. Psychophysiological methods; dynamic computational modeling methods; more recently, data fusion and big data. Quantum probabilistic and dynamic models of cognition and decision; contextualized communication, decision, and choices; more recently, extending the work to communication networks and a new theory for modeling networks.


6. [Cultural Brain](https://culturalbrain.org), lead by [Falk Huettig](https://www.mpi.nl/people/huettig-falk), at Max Planck Institute for Psycholinguistics, Nijmegen, the Netherlands. 

> Human cognition, and therefore the brain, is a product of both the cultural environment in which we are immersed and our genetic makeup. We explore how cultural inventions like written words, numbers, music, and belief systems shape the mind and brain from the beginning of our lives. Looking at the Literate Brain, the Predictive Brain, and the Multimodal Brain offers us a window into the culturally-shaped mind. Diverse groups, such as illiterates in India, young children, individuals with reading disorders and highly educated individuals take part in our studies. We use behavioural measures, functional and structural neuroimaging techniques, and computational modelling. In essence, we ask to what extent culture determines what it means to think as a human.

5. [The Markman Lab](http://markmanlab.stanford.edu/index.html), lead by Ellen M. Markman, at Stanford University, Stanford, CA.

> The Markman Lab, located in the Department of Psychology at Stanford University, focuses on a wide variety of topics in conceptual and language development. Our lab is led by Ellen M. Markman, Lewis M. Terman Professor of Psychology.

4. [The Language Learning Lab](http://web.sas.upenn.edu/trueswell-lab/), lead by Professor [John Trueswell](http://web.sas.upenn.edu/trueswell-lab/people/trueswell/), at University of Pennsylvania, Philadelphia, PA. 

> Welcome to the Language Learning Lab, located in the Department of Psychology at the University of Pennsylvania. Our research group investigates how people understand, produce, and learn language. The spoken language that you use everyday is very complex. You likely know not just tens of thousands of words, but also many grammatical rules about how to combine those words together to form sentences and communicate complex thoughts.

3. [Poeppel Lab](https://wp.nyu.edu/poeppellab/), lead by Professor [David Poeppel](http://as.nyu.edu/content/nyu-as/as/faculty/david-poeppel.html), at New York University, New York, NY.

> What neuronal and cognitive representations and operations form the basis for the transformation from “vibrations in the ear” (sounds) to “abstractions in the head” (words)? Broadly speaking, the Poeppel Lab investigates questions about language, speech, hearing, and music. The main methods employed include behavioral experiments, magnetoencephalography (MEG), functional magnetic resonance imaging (fMRI) – and whatever other methodology is appropriate for a given question. We are methodological pluralists.

2. [Language & Cognitive Dynamics Laboratory](http://www.danmirman.org/Home), lead by 

> We investigate language and cognitive processes and impairments using behavioral and eye-tracking experiments, computational modeling, and lesion-symptom mapping. Our major research focus areas are the organization of semantic knowledge, language deficits and recovery after left hemisphere stroke (aphasia), and the time course of spoken word comprehension. We aim for "Pasteur's Quadrant" -- to answer fundamental questions in cognitive science and neuroscience in a way that has practical applications, such as new insights into language impairments and helping to develop better rehabilitation strategies.

1. [Brain and Language Lab](https://brainlang.georgetown.edu), lead by Professor [Michael Ullman](https://georgetown.app.box.com/s/5lrbyhfe5iq07xim1b13t15tjx7m9hyl), at Georgetown University, Washington, D.C.

> The lab investigates the neurocognition of language and memory in healthy populations and disorders. To find out more, select an option from the menu. Listed below are some recent findings. 

# Institutes, Departments, and Schools
