---
title: Graphical Statistical Tools Based on R
author: ~
date: '2020-02-29'
slug: graphical-statistical-tools-based-on-r
categories: []
tags: []
output:
  blogdown::html_page:
    toc_depth: 6
    number_sections: true
    toc: true
---

# JASP

a. Website: [JASP-desktop](https://github.com/jasp-stats/jasp-desktop)

b. Introduction: JASP is an open-source statistics program that is free, friendly, and flexible. Armed with an easy-to-use GUI, JASP allows both classical and Bayesian analyses.

# jamovi

a. Website: __[https://www.jamovi.org/](https://www.jamovi.org/)__.

b. Introduction.

- STATS MADE SIMPLE <br>
    jamovi is a new “3rd generation” statistical spreadsheet. designed from the ground up to be easy to use, jamovi is a compelling alternative to costly statistical products such as SPSS and SAS.

- R INTEGRATION <br> 
    jamovi is built on top of the R statistical language, giving you access to the best the statistics community has to offer. would you like the R code for your analyses? jamovi can provide that too.

- FREE AND OPEN <br>
    jamovi will always be free and open - that's one of our core values - because jamovi is made by the scientific community, for the scientific community.

# R Commander

a. Website: __[The R Commander](https://socialsciences.mcmaster.ca/jfox/Misc/Rcmdr/index.html)__.

b.  Introduction

- The R Commander is a graphical user interface (GUI) to the free, open-source R statistical software. The R Commander is implemented as an R package, the Rcmdr package, which is freely available on CRAN (the R package archive).
