---
title: "Curriculum Vitae"
disable_comments: yes
date: '2016-01-22'
lastmod: "`r Sys.Date()`"
output:
  pdf_document:
    template: ~/Documents/ADMIN/Website/LaTex/my_pandoc_template.latex
    includes:
      in_header: ~/Documents/ADMIN/Website/LaTex/Preamble_Blogdown_CV.tex
    latex_engine: xelatex
    md_extensions: -autolink_bare_uris +hard_line_breaks
    keep_tex: false
  html_document:
    df_print: paged
  word_document: default
geometry: margin=1in
pdf: /en/cv/Likan_Zhan_CV_EN.pdf
type: cv
urlcolor: blue
fontsize: 12pt
---

# Likan ZHAN

- <i class="fas fa-university"> \faUniversity </i> &nbsp; No. 15, Xueyuan Road, Haidian District, Beijing 100083, China
- <i class="fas fa-phone"> \faPhone* </i> &nbsp; + 86 10 8230 3468
- <i class="far fa-envelope"> \faEnvelope[regular] </i> &nbsp; <zhanlikan@hotmail.com>
- <i class="fas fa-globe"> \faGlobe </i> &nbsp; <https://likan.info>
- Last update: `r Sys.Date()`

## Academic Appointment

- 2018.12 ~ Now, Associate professor,<br>
  School of Communication Science,<br>
  Beijing Language and Culture University, Beijing, China

- 2016.06 ~ 2018.11, Assistant professor,<br>
  School of Communication Science,<br>
  Beijing Language and Culture University, Beijing, China

- 2014.09 ~ 2016.05, Assistant professor,<br>
  Faculty of Linguistic Sciences,<br>
  Beijing Language and Culture University, Beijing, China

## Education

- 2010.10 ~ 2014.09, Ph.D. Cognitive Science, <br>
  Macquarie University, Sydney, Australia

- 2007.09 ~ 2010.07, M.E. Cognitive Psychology, <br>
  Beijing Language and Culture University, Beijing, China

- 2000.09 ~ 2004.07, B.A. Teaching Chinese as a Second Language, <br>
  Beijing Language and Culture University, Beijing, China


## Teaching Experience

- 2019 ~ Now. Experimental Psychology, <br>
  Undergraduates, 4 hours per week, 68 hours in total

- 2019 ~ Now. Introduction to Neurolinguistics, <br>
  Postgraduates, 2 hours per week, 34 hours in total

- 2017 ~ Now. Statistics for the Behavioral Sciences, <br>
  Undergraduates and Postgraduates, 2 hours per week, 34 hours in total

- 2016 ~ Now. R for Modeling and Visualizing Data, <br>
  Postgraduates and PhD candidates, 4 hours per week, 68 hours in total

- 2015 ~ Now. Introduction to Cognitive Neuroscience,  <br>
  Postgraduates and PhD candidates, 2 hours per week, 34 hours in total

- 2015 ~ Now. Foundations of Scientific Research, <br>
  Undergraduates, 3 hours per week, 54 hours in total

- 2015 Fall. General Psychology, <br>
  Undergraduates, 3 hours per week, 54 hours in total

## Professional Skills

1. Experiment techniques

- Test stimuli: Package [PGF](https://ctan.org/pkg/pgf?lang=en) in [LaTeX](https://www.latex-project.org), [ImageMagick](https://imagemagick.org) and its implementation in R [magick](https://cran.r-project.org/web/packages/magick/index.html), [OmniGraffle](https://www.omnigroup.com/omnigraffle/), as well as [Pixelmator](https://www.pixelmator.com) for image creating and editting; [praat](http://www.fon.hum.uva.nl/praat/), Packages [tuneR](https://cran.r-project.org/web/packages/tuneR/index.html) and [seewave](https://cran.r-project.org/package=seewave) in R, as well as [Adobe Audition](https://www.adobe.com/products/audition.html) for audio editing and processing; [blender](https://www.blender.org) and [Autodesk Maya](https://www.autodesk.com/products/maya/overview) for video and 3d modeling; and [ffmpeg](https://ffmpeg.org) for audio and video format converting;

- Experiments building: Be familiar with package [Psychtoolbox](http://psychtoolbox.org) under [Matlab](https://www.mathworks.com/products/matlab.html), [Presentation](https://www.neurobs.com/presentation), package [Psychopy](http://www.psychopy.org) under [Python](https://www.python.org), [E-prime](https://www.pstnet.com/eprime.cfm), and [Experiment Builder](https://www.sr-research.com/experiment-builder/) for script building;

- Eye-tracker: Having advanced experience in using [Eyelink II/1000 plus](https://www.sr-research.com) for experiment conducting, [Experiment Builder](https://www.sr-research.com/experiment-builder/) for experiment building, and [Data Viewer](https://www.sr-research.com/data-viewer/) for data pre-processing;

- E/MEG: In charge of establishing the first Child MEG lab in China; be familiar with Yokogawa MEG system for equipment maintenance and MEG data acquisition, packages [fieldtrip](http://www.fieldtriptoolbox.org) and [SPM12](https://github.com/neurodebian/spm12) under Matlab, and [BESA](http://www.besa.de) for data processing.

2. Data processing

- R: Besides base [R](https://www.r-project.org), be familiar with [data.table](http://r-datatable.com), [dplyr](https://cran.r-project.org/web/packages/dplyr/index.html), and [tidyr](https://cran.r-project.org/web/packages/tidyr/index.html) etc. for data preprocessing; [graphics](https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/00Index.html), [lattice](https://cran.r-project.org/package=lattice), and [ggplot2](http://ggplot2.tidyverse.org) etc. for data visualization; [car](https://cran.r-project.org/web/packages/car/index.html), [lme4](https://github.com/lme4/lme4), and [gam](https://cran.r-project.org/web/packages/gam/index.html) for computational modeling. Create the R package [acqr](https://github.com/likanzhan/acqr) etc. for teaching statistics and illustrating data visualization;

- Julia: Recently start to use [julia](https://julialang.org), because of the [speed limitations](https://julialang.org/benchmarks/) of R. Besides the base and standard libraries, be familiar with [CSV.jl](https://github.com/JuliaData/CSV.jl), [DataFrames.jl](https://github.com/JuliaData/DataFrames.jl) ([Database benchmark](https://h2oai.github.io/db-benchmark/)), and [DataFramesMeta.jl](https://github.com/JuliaData/DataFramesMeta.jl) etc. for data preprocessing; [Plots.jl](https://github.com/JuliaPlots/Plots.jl), [StatsPlots.jl](https://github.com/JuliaPlots/StatsPlots.jl), and [Gadfly.jl](https://github.com/GiovineItalia/Gadfly.jl) for data visualization; as well as [Distributions.jl](https://github.com/JuliaStats/Distributions.jl), [StatsBase.jl](https://github.com/JuliaStats/StatsBase.jl), [StatsModels.jl](https://github.com/JuliaStats/StatsModels.jl), [GLM.jl](https://github.com/JuliaStats/GLM.jl), and [MixedModels.jl](https://github.com/JuliaStats/MixedModels.jl) for computational modeling;

3. Other

- Markup languages: Be familiar with [LaTeX](https://www.latex-project.org), [markdown](https://daringfireball.net/projects/markdown/), [R markdown](https://rmarkdown.rstudio.com) (R flavoured markdown), [Pluto.jl](https://github.com/fonsp/Pluto.jl) (julia package), and [Jupyter](https://jupyter.org) for document preparing; [knitr](https://cran.r-project.org/web/packages/knitr/index.html) (R package) [Documenter.jl](https://github.com/JuliaDocs/Documenter.jl) and [Weave.jl](https://github.com/JunoLab/Weave.jl) (Julia package) for dynamically integrating R or Julia source code into a document; [Pandoc](https://pandoc.org) for format conversion;

- Be familiar with the free source-code editor [visual studio code](https://code.visualstudio.com);

- Be familiar with the distributed version control system [git](https://git-scm.com), package managers [conda](https://docs.conda.io/en/latest/), [homebrew](https://brew.sh), and [npm](https://www.npmjs.com);

- Personal website: Use [hugo](https://gohugo.io) under [go](https://golang.org) language and the R package [blogdown](https://github.com/rstudio/blogdown) to build my personal website [https://likan.info](https://likan.info).

## Grants, Projects, and Awards

1. Grants

- **Zhan, L.**, Zhou, P., Zhang, L., & Crain, S. (2019 - 2023). The acquisition and online processing of irrealis in Mandarin Chinese. *The National Social Science Fund of China*. [Grant No. 19BYY087]. (¥200,000). Role: Principle Investigator.

- **Zhan, L.**, Qu, Y., Xu, J., Xiao, Y., & Li, N. (2019 - 2020). The eye movements pattern and neural oscitation markers of predictive processing in language comprehension. *The Fundamental Research Funds for the Central Universities*. [Grant No. 19YJ080002]. (¥70,000). Role: Principle Investigator.

- **Zhan, L.**, Shi, F., Gao, L., & Zhang, L. (2019 - 2020). The online processing and acquisition of lexical tone in Mandarin Chinese. *The Fundamental Research Funds for the Central Universities*. [Grant No. 18YBT15]. (¥70,000). Role: Principle Investigator.

- Shi, D., et al. (2018 - 2023). Studies of Chinese in Generative Grammar and Development of Chinese Grammar in the New Era. *The Major Project of the National Social Science Found of China*. [Grant No. 18ZDA291]. (¥800,000). Role: Co-Investigator.

- Si, F., et al. (2018 - 2023). Language acquisition and language cognition under the perspective of syntactic cartography. *The Fundamental Research Funds for the Central Universities*. [Grant No. 18ZDJ06]. (¥300,000). Role: Co-Investigator.

- **Zhan, L.** (2015 - 2016). Experimental explorations of possible world semantics. *The Fundamental Research Funds for the Central Universities*. [Grant No. 15YBB29]. (¥20,000). Role: Principle Investigator.

- **Zhan, L.** (2015 - 2016). Introduction to psychology and the scientific research. *The Funds Supporting the Growth of the New Teachers*. [Grant No. FD201530]. (¥7,000). Role: Principle Investigator.

- **Zhan, L.**, Shi, F., Gao, L., & Zhang, L. (2015 - 2016). The Processing and acquisition of tone in Mandarin Chinese. *The Fundamental Research Funds for the Central Universities*. [Grant No. 15YJ050003]. (¥70,000). Role: Principle Investigator.

- **Zhan, L.** (2010 - 2014). The interpretation of conditionals in natural language. *Cognitive Science Postgraduate Research Grant of Macquarie University*. ($10,570). Role: Principle Investigator.

- **Zhan, L.** (20103). The hypothetical property of conditionals in natural language. *Macquarie University Postgraduate Research Fund*. ($4,684). Role: Principle Investigator.

2. Projects

- Zhang, L., et al. (2018 - Now). The psychological and brain development of atypical developing adolescences. *The Program of WuTong Innovations Platforms*. Role: Co-Investigator.

- Chen, M., et al. (2019 - Now). The study of Chinese as a second language acquisition and second language teaching (The JunCai Group). *The Program of Establishing First-Class Disciplines in BLCU*. Role: Co-Investigator.

3. Awards

- 2013.11. The Paula Menyuk Travel Award for the 38th Boston University Conference on Language Development. ($300).

- 2013.04. The Travel Award for the 26th Annual CUNY Sentence Processing Conference. ($350).

## Professional Activities

1. Frontiers in Psychology, Review Editor in Language Sciences (2020 - )

2. Organization of international meetings

- Academic Advisory Committee, The 24th annual conference of the International Association of Chinese Linguistics ([IACL-24](http://iacl24.blcu.edu.cn)), Beijing Language and Culture University, Beijing, China.

3. Ad-hoc reviews

- Frontiers in Psychology. (2020 - )
- Scientific Reports. (2018 - 2019);
- Journal of visualized experiments. (2018 - 2019);
- Language Teaching and Linguistic Studies. (In Chinese, 2016);
- SAGE Open. (2016).

4. Clinical licenses

- Licensed Examiner of Wechsler Preschool and Primary Scale of Intelligence 4th Edition (WPPSI-VI) Chinese Version.

- Licensed Examiner of Adaptive Behavior Assessment System 2nd Edition (ABAS-II) Chinese Version.

## Publications

1. Book

- **Zhan, L.** (2015). *The Interpretation of Conditionals in Natural Language*. Saarbrucken, Germany: Lap Lambert Academic Publishing.

2. Periodicals

- Zhou, P., Shi, J., & **Zhan, L.** (in press). Real-time comprehension of garden-path constructions by preschoolers: A Mandarin perspective. *Applied Psycholinguistics*.

- Zhou, P., Ma, W., & **Zhan, L.** (2019). A deficit in using prosodic cues to understand communicative intentions by children with autism spectrum disorders: An eye-tracking study. *First Language*. doi: 10.1177/0142723719885270 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/FirstLang2019.pdf)

- Zhou, P., **Zhan, L.**, & Ma, H. (2019). Understanding others' minds: Social inference in preschool children with autism spectrum disorder. *Journal of Autism and Developmental Disorders, 49*(11), 4523-4534. doi: 10.1007/s10803-019-04167-x [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/JAutismDevDisord2019.pdf)

- Zhou, P., **Zhan, L.**, & Ma, H. (2019). Predictive language processing in preschool children with Autism Spectrum Disorder: An eye-tracking study. *Journal of Psycholinguistic Research, 48*(2), 431-452. doi: 10.1007/s10936-018-9612-5 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/JPsycholinguistRes2018.pdf)

- **Zhan, L.** (2018). Using eye movements recorded in the visual world paradigm to explore the online processing of spoken language. *Journal of Visualized Experiments, 140*, e58086. doi: 10.3791/58086 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/jove-protocol-58086.pdf)

- Zhou, P., Ma, W., **Zhan, L.**, & Ma, H (2018). Using the visual world paradigm to study sentence comprehension in Mandarin-speaking children with autism. *Journal of Visualized Experiments, 140*, e58452. doi: 10.3791/58452 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/jove-protocol-58452.pdf)

- **Zhan, L.**, Zhou, P., & Crain, S. (2018). Using the visual-world paradigm to explore the meaning of conditionals in natural language. *Language, Cognition and Neuroscience, 33*(8), 1049-1062. doi: 10.1080/23273798.2018.1448935 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/LangCognNeurosci2018.pdf)

- **Zhan, L.** (2018). Scalar and ignorance inferences are both computed immediately upon encountering the sentential connective: The online processing of sentences with disjunction using the visual world paradigm. *Frontiers in Psychology, 9*. doi: 10.3389/fpsyg.2018.00061  [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://www.frontiersin.org/articles/10.3389/fpsyg.2018.00061/full)

- Moscati, V., **Zhan, L.**, & Zhou, P. (2017). Children's on-line processing of epistemic modals. *Journal of Child Language, 44*(5), 1025-1040. doi: 10.1017/S0305000916000313 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/JChildLang2016.pdf)

- **Zhan, L.**, Crain, S., & Zhou, P. (2015). The online processing of only if- and even if- conditional statements: Implications for mental models. *Journal of Cognitive Psychology, 26*(7), 367-379. doi: 10.1080/20445911.2015.1016527 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/JCognPsychol2015.pdf)

- Zhou, P., Crain, S., & **Zhan, L.** (2014). Grammatical aspect and event recognition in children's online sentence comprehension. *Cognition, 133*(1), 262-276. doi: 10.1016/j.cognition.2014.06.018 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](http://publications.likan.info/Periodicals/Cognition2014.pdf)

- Zhou, P., Crain, S., & **Zhan, L.** (2012). Sometimes children are as good as adults: The pragmatic use of prosody in children’s on-line sentence processing. *Journal of Memory and Language, 67*(1), 149-164. doi: 10.1016/j.jml.2012.03.005 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/JMemLang2012.pdf)

- Zhou, P., Su, Y., Crain, S., Gao, L., & **Zhan, L.** (2012). Children's use of phonological information in ambiguity resolution: A view from Mandarin Chinese. *Journal of Child Language, 39*(04), 687-730. doi: 10.1017/S0305000911000249 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/JChildLang2012.pdf)

3. Book chapters and conference proceedings

- **Zhan, L.** (2018). Magnetoencephalography (MEG) as a Technique for Imaging Brain Function and Dysfunction. In *Top 10 Contributions on Psychology* (Chapter 4, pp. 1-38). Telangana, India: Avid Science

- **Zhan, L.**, Crain, S., & Zhou, P. (2013). The anticipatory effects of focus operators: A visual-world paradigm eye-tracking study of “only if” and “even if” conditionals. In N. Goto, K. Otaki, A. Sato, & K. Takita (Eds.), *Proceedings of GLOW in Asia IX 2012*. Mie University, Japan.

4. Peer reviewed conference presentations

- **Zhan, L.**, & Zhou, P. (2019, June). *Children differ from adults in interpreting disjunctions: Evidence from an eye-tracking study*. Poster session presented at Psycholinguistics in Iceland - Parsing and Prediction, University of Iceland, Reykjavík, Iceland. [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Talks/PIPP_Poster.pdf)

- **Zhan, L.** (2017, September). *Scalar implicature and ignorance inference are both locally computed: Evidence from the online processing of disjunctions using the visual world paradigm*. Oral session presented at the Second High-level Forum on Cognitive Linguistics, University of International Business and Economics, Beijing, China. [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Talks/ZhanL2017UIBE.pdf)

- **Zhan, L.**, Crain, S., & Zhou, P. (2013, November). *Going beyond the information that is perceived: The hypothetical property of if-conditionals in Mandarin Chinese*. Oral session presented at the Second International Conference on Psycholinguistics in China, Fuzhou, China.

- Moscati, V., **Zhan, L.**, & Zhou, P. (2013, November). *Reasoning on possibilities: An eye tracking study on modal knowledge*. Poster session presented at the 38th Annual Boston University Conference on Language Development, Boston University, MA.

- Zhou, P., Crain, S., & **Zhan, L.** (2013, November). *Anticipatory eye movements in children’s processing of grammatical aspect*. Poster session presented at the 38th Annual Boston University Conference on Language Development, Boston University, MA.

- **Zhan, L.**, Crain, S., & Zhou, P. (2013, March). *The hypothetical property of “if”-statements: A visual-world paradigm eye-tracking study*. Poster session presented at CUNY2013: The 26th annual CUNY Sentence Processing Conference, Columbia, SC.

- **Zhan, L.**, Crain, S., & Zhou, P. (2012, July). *The interpretation of conditionals*. Oral session presented at the 7th International Conference on Thinking (ICT2012), Birkbeck/UCL, London, UK.

- Zhou, P., Crain, S., & **Zhan, L.** (2012, March). *Children’s pragmatic use of prosody in sentence processing*. Poster session presented at the 35th Generative Linguistics in the Old World (GLOW) Workshop: Production and Perception of Prosodically-Encoded Information Structure, University of Potsdam, Potsdam, Germany.

- **Zhan, L.**, Crain, S., & Khlentzos, D. (2011, August). *The basic semantics of conditionals in natural language*. Oral session presented at the Harvard-Australia Workshop on Language, Learning and Logic, Macquarie University, Sydney, Australia.

- Zhou, P., Crain, S., Gao, L., & **Zhan, L.** (2010, September). *The role of prosody in children’s focus identification*. Oral session presented at the Generative Approaches to Language Acquisition - North America 4 (GALANA-4), Toronto, Canada.

- Zhou, P., Su, Y., Crain, S., Gao, L., & **Zhan, L.** (2010, August). *Children’s use of prosodic information in ambiguity resolution*. Oral session presented at the 8th Conference of Generative Linguistics in the Old World Asia (GLOW-in-Asia 8), Beijing, China.

5. Invited talks

- **Zhan, L.** (2019, August). *Gardener or Carpenter: Some thoughts on nurturing a child*. Invited presentation given at Smiland Daycare Center. [<i class="fas fa-external-link-alt fa-sm"> \footnotesize \faExternalLink* </i>](https://publications.likan.info/talks/parent/)

- **Zhan, L.** (2018, December). *Sentential reasoning and sentential connectives: Conditional, disjunction, negation, and modality*. Invited presentation given at the Workshop of Theoretical and Experimental Linguistics, Tsinghua University, Beijing, China. [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Talks/Sentential_Reasoning_Sentential_Connectives.pdf)

- **Zhan, L.** (2018, November). *Methods of cognitive neuroscience: Focus on language*. Invited presentation given at the Child Cognition Laboratory, Department of Foreign Languages and Literatures, Tsinghua University, Beijing, China. [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Talks/MethodsCognNeurosciLang2018NOV.pdf)

- **Zhan, L.** (2018, November). *Visual world paradigm: An eye-tracking technique to study the real time processing of spoken Language*. Invited presentation given at the Center for Studies of Chinese as a Second Language, Beijing Language and Culture University, Beijing, China. [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Talks/Visual_World_Paradigm.pdf)

- **Zhan, L.** (2018, October). *Experimental Builder: A what-you-see-is-what-you-get tool to build experiment scripts*. Invited presentation given at the Center for Studies of Chinese as a Second Language, Beijing Language and Culture University, Beijing, China. [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Eyelink_Experiment_Builder_Training_Materials/)