---
title: "简历"
disable_comments: yes
date: '2016-01-22'
lastmod: "`r Sys.Date()`"
output:
  pdf_document:
    includes:
      in_header: ~/Documents/ADMIN/Website/LaTex/Preamble_Blogdown_CV.tex
    latex_engine: xelatex
    md_extensions: -autolink_bare_uris +hard_line_breaks
    keep_tex: false
geometry: margin=1in
pdf: /cn/cv/Likan_Zhan_CV_CN.pdf
type: cv
urlcolor: blue
fontsize: 12pt
---

# 战立侃

- <i class="fas fa-university">\faUniversity</i> &nbsp; 北京市海淀区学院路15号，北京语言大学，综合楼1235室
- <i class="fas fa-phone">\faPhone*</i> &nbsp; + 86 10 8230 3468
- <i class="far fa-envelope">\faEnvelope[regular]</i> &nbsp; <zhanlikan@hotmail.com>
- <i class="fas fa-globe">\faGlobe</i> &nbsp; <https://likan.info>
- 最近更新：`r Sys.Date()`

## 职业经历

- 2019.07 ~ 现在，副教授，北京语言大学语言康复学院

- 2014.10 ~ 2019.06，助理研究员，北京语言大学语言病理与脑科学研究所

## 教育经历

- 2010.10 ~ 2014.09，澳大利亚麦考瑞大学，认知科学专业，哲学博士

- 2007.09 ~ 2010.07，北京语言大学，认知心理学专业，教育学硕士

- 2000.09 ~ 2004.07，北京语言大学，对外汉语教学专业，文学学士

## 教学经历

- 2019 ~ 现在，实验心理学，<br>
  每周4课时，共68课时，言语听觉本科生

- 2017 ~ 现在，行为科学统计学，<br>
  每周2课时，共34课时，言语听觉本科生和相关专业硕士研究生

- 2016 ~ 现在，R语言与数据统计和数据可视化，<br>
  每周4课时，共68课时，相关专业硕士和博士研究生

- 2015 ~ 现在，认知神经科学导论，<br>
  每周2课时，共34课时，言语听觉本科生和相关专业硕博士研究生

- 2015 ~ 现在，医学文献检索与阅读，<br>
  每周3课时，共54课时，言语听觉本科生

- 2015年秋，普通心理学，<br>
  每周3课时，共54课时，言语听觉本科生

## 专业技能

1. 实验技能

- 实验材料：能用 [LaTeX](https://www.latex-project.org) 包 [PGF](https://ctan.org/pkg/pgf?lang=en)、 [ImageMagick](https://imagemagick.org)、R包 [magick](https://cran.r-project.org/web/packages/magick/index.html)、 [OmniGraffle](https://www.omnigroup.com/omnigraffle/) (非开源)、和 [Pixelmator](https://www.pixelmator.com) (非开源) 等设计和编辑测试用图片；用 [praat](http://www.fon.hum.uva.nl/praat/)、R包 [tuneR](https://cran.r-project.org/web/packages/tuneR/index.html)、[seewave](https://cran.r-project.org/package=seewave)、和 [Adobe Audition](https://www.adobe.com/products/audition.html) (非开源) 等编辑测试用声音材料；用 [blender](https://www.blender.org) 和 [Autodesk Maya](https://www.autodesk.com/products/maya/overview) (非开源) 等设计和编辑视频及三维材料；用 [ffmpeg](https://ffmpeg.org) 等转化视频和音频文件的格式；
- 实验设计: 能用 [Python](https://www.python.org) 下的 [Psychopy](http://www.psychopy.org) 包、 [Matlab](https://www.mathworks.com/products/matlab.html) 下的 [Psychtoolbox](http://psychtoolbox.org) 包、 [E-prime](https://www.pstnet.com/eprime.cfm) (非开源)、 [Presentation](https://www.neurobs.com/presentation)  (非开源), 和 [Experiment Builder](https://www.sr-research.com/experiment-builder/)  (非开源) 等设计实验程序；
- 眼动技术: 熟悉 [Eyelink II/1000 plus](https://www.sr-research.com) 型眼动仪、 能用 [Experiment Builder](https://www.sr-research.com/experiment-builder/) 进行实验程序的设计和 [Data Viewer](https://www.sr-research.com/data-viewer/) 进行数据分析；
- 脑电/磁图仪：主持建立了中国第一个儿童脑磁图实验室; 熟悉日本 Yokogawa 脑磁图仪的设备维护和数据采集；能用 [BESA](http://www.besa.de)、 [fieldtrip](http://www.fieldtriptoolbox.org)、和 [SPM12](https://github.com/neurodebian/spm12) 等对脑电/磁数据进行分析。

2. 数据分析

- R语言：除了 [R](https://www.r-project.org) 基本包外，擅长用 [data.table](http://r-datatable.com)、 [dplyr](https://cran.r-project.org/web/packages/dplyr/index.html)、和 [tidyr](https://cran.r-project.org/web/packages/tidyr/index.html) 对数据进行预处理; 用 [graphics](https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/00Index.html)、 [lattice](https://cran.r-project.org/package=lattice)、和 [ggplot2](http://ggplot2.tidyverse.org) 等对数据进行可视化分析；用 [car](https://cran.r-project.org/web/packages/car/index.html)、[lme4](https://github.com/lme4/lme4)、和 [gam](https://cran.r-project.org/web/packages/gam/index.html) 等进行计算模型模拟；自己编写了R包 [acqr](https://github.com/likanzhan/acqr) 以辅助统计教学和数据可视化展示；
- Julia语言：由于R语言在计算速度上的不足，近期开始使用 [julia](https://julialang.org) 语言，尤其是包 [MixedModels](https://github.com/dmbates/MixedModels.jl) 开展数据分析。

3. 其他技能

- 标记语言：喜欢用 [LaTeX](https://www.latex-project.org)、[markdown](https://daringfireball.net/projects/markdown/)
和 [R markdown](https://rmarkdown.rstudio.com) (R包) 等进行学术写作和排版；用 [knitr](https://cran.r-project.org/web/packages/knitr/index.html)（R包）把R语言代码嵌入文本写作中；用 [Pandoc](https://pandoc.org) 在文件的不同格式间进行转换；
- 个人网站：用 [go](https://golang.org) 语言下的 [hugo](https://gohugo.io) 和R语言下的 [blogdown](https://github.com/rstudio/blogdown) 包建立了的个人网站 [https://likan.info](https://likan.info)。


## 科研项目、合作平台和奖励

1. 项目

- 2019 ~ 2023，现代汉语非现实句的在线加工和习得研究，*国家社会科学基金一般项目*，[批准号：19BYY087]，20万，主持人

- 2019 ~ 2020，语言理解中预测性加工的眼动和神经振荡模式研究，*北京语言大学院级团队项目*，[批准号：19YJ080002]，7万，主持人

- 2019 ~ 2023，生成语法的汉语研究与新时代汉语语法理论创新，*国家社科基金重大项目*，[批准号：18ZDA291]，80万，参与者

- 2019 ~ 2020，现代汉语声调加工和习得研究，*北京语言大学校级一般项目*，[批准号：18YBT15]，7万，主持人

- 2018 ~ 2023，句法制图视角下的语言习得与认知研究，*北京语言大学校级重大项目*，[批准号：18ZDJ06], 30万，子项目负责人

- 2015 ~ 2016，可能世界语义学的实验研究，*北京语言大学博士科研启动金*，[批准号：15YBB29]，2万，主持人

- 2015 ~ 2016，普通心理学，*北京语言大学新任教师支持基金*，[批准号：FD201530]，0.7万，主持人

- 2015 ~ 2016，现代汉语声调习得研究，*北京语言大学院级项目*，[批准号：15YJ050003]，7万，主持人

- 2010 ~ 2014，自然语言中条件句的理解，*麦考瑞大学认知科学博士生项目*，1万澳元，主持人

- 2013.10，自然语言中条件句假设特征研究，*麦考瑞大学博士生研究基金*，0.46万澳元, 主持人

2. 合作平台  

- 2019 ~ 现在，汉语作为第二语言的习得和教学研究创新团队，*北京语言大学一流学科团队建设计划（隽才计划）*，参与者

- 2018 ~ 现在，特殊儿童青少年的心智发展和脑发育特征研究创新平台，*北京语言大学梧桐创新平台*，参与者

3. 奖励  

- 2013.11：第38届波士顿儿童语言发展研讨会，旅行奖励 300 美元  

- 2013.04：第26届纽约城市大学句子加工会议，旅行奖励 350 美元  

## 学术兼职  

1. 会议组织

- 国际中国语言学会第24届年会，会务组和咨询委员会委员，2016年7月17日-19日， 中国北京，北京语言大学

2. 匿名评审

- Scientific Reports. (2018 - 2019)
- Journal of visualized experiments. (2018 - 2019)
- Language Teaching and Linguistic Studies. (In Chinese, 2016)
- SAGE Open. (2016)

3. 执业资格

- 韦氏婴幼儿智力量表第四版（WPPSI-VI）中文版主试资格

- 适应性行为评定量表第二版（ABAS-II）中文版主试资格

## 出版物

1. 专著

- **Zhan, L.** (2015). *The Interpretation of Conditionals in Natural Language*. Saarbrucken, Germany: Lap Lambert Academic Publishing.

2. 杂志论文

- Zhou, P., **Zhan, L.**, & Ma, H. (2019). Understanding Others' Minds: Social Inference in Preschool Children with Autism Spectrum Disorder. *Journal of Autism and Developmental Disorders*. doi:10.1007/s10803-019-04167-x [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/JAutismDevDisord2019.pdf)

- Zhou, P., **Zhan, L.**, & Ma, H. (2018). Predictive language processing in preschool children with Autism Spectrum Disorder: An eye-tracking study. *Journal of Psycholinguistic Research*. doi:10.1007/s10936-018-9612-5 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/JPsycholinguistRes2018.pdf)

- **Zhan, L.** (2018). Using eye movements recorded in the visual world paradigm to explore the online processing of spoken language. *Journal of Visualized Experiments, 140*, e58086. doi: 10.3791/58086 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/jove-protocol-58086.pdf)

- Zhou, P., Ma, W., **Zhan, L.**, & Ma, H (2018). Using the visual world paradigm to study sentence comprehension in Mandarin-speaking children with autism. *Journal of Visualized Experiments, 140*, e58452. doi: 10.3791/58452 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/jove-protocol-58452.pdf)

- **Zhan, L.**, Zhou, P., & Crain, S. (2018). Using the visual-world paradigm to explore the meaning of conditionals in natural language. *Language, Cognition and Neuroscience, 33*(8), 1049-1062. doi: 10.1080/23273798.2018.1448935 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/LangCognNeurosci2018.pdf)

- **Zhan, L.** (2018). Scalar and ignorance inferences are both computed immediately upon encountering the sentential connective: The online processing of sentences with disjunction using the visual world paradigm. *Frontiers in Psychology, 9*. doi: 10.3389/fpsyg.2018.00061  [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://www.frontiersin.org/articles/10.3389/fpsyg.2018.00061/full)

- Moscati, V., **Zhan, L.**, & Zhou, P. (2017). Children's on-line processing of epistemic modals. *Journal of Child Language, 44*(5), 1025-1040. doi: 10.1017/S0305000916000313 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/JChildLang2016.pdf)

- **Zhan, L.**, Crain, S., & Zhou, P. (2015). The online processing of only if- and even if- conditional statements: Implications for mental models. *Journal of Cognitive Psychology, 26*(7), 367-379. doi: 10.1080/20445911.2015.1016527 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/JCognPsychol2015.pdf)

- Zhou, P., Crain, S., & **Zhan, L.** (2014). Grammatical aspect and event recognition in children's online sentence comprehension. *Cognition, 133*(1), 262-276. doi: 10.1016/j.cognition.2014.06.018 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](http://publications.likan.info/Periodicals/Cognition2014.pdf)

- Zhou, P., Crain, S., & **Zhan, L.** (2012). Sometimes children are as good as adults: The pragmatic use of prosody in children’s on-line sentence processing. *Journal of Memory and Language, 67*(1), 149-164. doi: 10.1016/j.jml.2012.03.005 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/JMemLang2012.pdf)

- Zhou, P., Su, Y., Crain, S., Gao, L., & **Zhan, L.** (2012). Children's use of phonological information in ambiguity resolution: a view from Mandarin Chinese. *Journal of Child Language, 39*(04), 687-730. doi: 10.1017/S0305000911000249 [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Periodicals/JChildLang2012.pdf)

3. 会议论文集

- **Zhan, L.** (2018). Magnetoencephalography (MEG) as a Technique for Imaging Brain Function and Dysfunction. In *Top 10 Contributions on Psychology* (Chapter 4, pp. 1-38). Telangana, India: Avid Science

- **Zhan, L.**, Crain, S., & Zhou, P. (2013). The anticipatory e ects of focus operators: A visual- world paradigm eye-tracking study of “only if” and “even if” conditionals. In N. Goto, K. Otaki, A. Sato, & K. Takita (Eds.), *Proceedings of GLOW in Asia IX 2012*. Mie University, Japan.

4. 同行评审的大会报告

- **Zhan, L.**, & Zhou, P. (2019, June). *Children differ from adults in interpreting disjunctions: Evidence from an eye-tracking study *. Poster session presented at Psycholinguistics in Iceland - Parsing and Prediction, University of Iceland, Reykjavík, Iceland. [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Talks/PIPP_Poster.pdf)

- **Zhan, L.** (2017, September). *Scalar implicature and ignorance inference are both locally computed: Evidence from the online processing of disjunctions using the visual world paradigm*. Paper presented at the Second High-level Forum on Cognitive Linguistics, University of International Business and Economics, Beijing, China. [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Talks/ZhanL2017UIBE.pdf)

- **Zhan, L.**, Crain, S., & Zhou, P. (2013, November). *Going beyond the information that is perceived: The hypothetical property of if-conditionals in Mandarin Chinese*. Paper session presented at the Second International Conference on Psycholinguistics in China, Fuzhou, China.

- Moscati, V., **Zhan, L.**, & Zhou, P. (2013, November). *Reasoning on possibilities: An eye tracking study on modal knowledge*. Poster session presented at the 38th Annual Boston University Conference on Language Development, Boston University, MA.

- Zhou, P., Crain, S., & **Zhan, L.** (2013, November). *Anticipatory eye movements in children’s processing of grammatical aspect*. Poster session presented at the 38th Annual Boston University Conference on Language Development, Boston University, MA.

- **Zhan, L.**, Crain, S., & Zhou, P. (2013, March). *The hypothetical property of “if”-statements: A visual- world paradigm eye-tracking study*. Poster session presented at CUNY2013: The 26th annual CUNY Sentence Processing Conference, Columbia, SC.

- **Zhan, L.**, Crain, S., & Zhou, P. (2012, July). *The interpretation of conditionals*. Paper presented at the 7th International Conference on Thinking (ICT2012), Birkbeck/UCL, London, UK.

- Zhou, P., Crain, S., & **Zhan, L.** (2012, March). *Children’s pragmatic use of prosody in sentence processing*. Poster session presented at the 35th Generative Linguistics in the Old World (GLOW) Workshop: Production and Perception of Prosodically-Encoded Information Structure, University of Potsdam, Potsdam, Germany.

- **Zhan, L.**, Crain, S., & Khlentzos, D. (2011, August). *The basic semantics of conditionals in natural language*. Paper presented at the Harvard-Australia Workshop on Language, Learning and Logic, Macquarie University, Sydney, Australia.

- Zhou, P., Crain, S., Gao, L., & **Zhan, L.** (2010, September). *The role of prosody in children’s focus identification*. Paper presented at the Generative Approaches to Language Acquisition - North America 4 (GALANA-4), Toronto, Canada.

- Zhou, P., Su, Y., Crain, S., Gao, L., & **Zhan, L.** (2010, August). *Children’s use of prosodic information in ambiguity resolution*. Paper presented at the 8th Conference of Generative Linguistics in the Old World Asia (GLOW-in-Asia 8), Beijing, China.

5. 受邀报告

- **Zhan, L.** (2019, August). *Gardener or Carpenter: Some thoughts on nurturing a child*. Invited Presentation given at Smiland Daycare Center. [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/talks/parent/)

- **Zhan, L.** (2018, December). *Sentential Reasoning and Sentential Connectives: Conditional, Disjunction, Negation, and Modality*. Inivted presentation given at the Workshop of Theoretical and Experimental Linguistics, Tsinghua University, Beijing, China. [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Talks/Sentential_Reasoning_Sentential_Connectives.pdf)

- **Zhan, L.** (2018, November). *Methods of Cognitive Neuroscience: Focus on Language*. Inivted presentation given at the Child Cognition Laboratory, Department of Foreign Languages and Literatures, Tsinghua University, Beijing, China. [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Talks/MethodsCognNeurosciLang2018NOV.pdf)

- **Zhan, L.** (2018, November). *Visual world paradigm: An eye-tracking technique to study the real time processing of spoken Language*. Inivted presentation given at the Center for Studies of Chinese as a Second Language, Beijing Language and Culture University, Beijing, China. [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Talks/Visual_World_Paradigm.pdf)

- **Zhan, L.** (2018, October). *Experimental Builder: A What-You-See-Is-What-You-Get tool to build experiment scripts*. Inivted presentation given at the Center for Studies of Chinese as a Second Language, Beijing Language and Culture University, Beijing, China. [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://publications.likan.info/Eyelink_Experiment_Builder_Training_Materials/)
