---
title: "Statistics for the Behavioral Sciences"
author: "Likan Zhan"
date: '2017-03-01'
lastmod: "2021-09-06"
show_toc: yes
disable_comments: yes
output:
  blogdown::html_page:
    toc: yes
---

# 1. Time and Location

- Time: 08:00 - 11:00, Tuesday
- Location: Room 106, Main Building South
- Lecturer: Likan Zhan

# 2. Course Information

Statistical procedures provide researchers with objective and systematic methods for describing and interpreting their research results. Scientific research is the system that we use to gather information, and statistics are the tools that we use to distill the information into sensible and justified conclusions. The goal of this course is not only to teach the methods of statistics, but also to convey the basic principles of objectivity and logic that are essential for science and valuable for decision making in everyday life.

This course is an introductory course of *Statistics for the the Behavioral Sciences*. A primary goal of this course is to make the task of learning statistics as easy and painless as possible. Topics of this course include Frequency Distribution, Centtral Tendency, Variability, z-scores, Probability and Samples, Hypothesis Testing, t-test, ANOVA, Correlation, Regression, Chi-Square test, and Binomal test etc. At the end of the course you should be able to read behavioural research that uses basic statistical methods; to undertake elementary data analysis; and to take more advanced courses in statistics, such as the course *Data Science With Julia*. More specifically, you will learn:

- to summarize statistical data and to discover patterns in data;
- to draw inferences from a sample to a larger population from which the sample was drawn; and
- to use the computer software `R` to analyze statistical data.

<!--

本课程是心理统计学的入门课程，授课对象为本科生高年级学生。本课程内容包括统计学简介、频率分布、集中量数、变异量数、正态分布和z分数、概率、样本和概率、假设检验、t检验（t检验简介、独立样本t检验和相关样本t检验）、方差分析（方差分析简介、重复测量的方差分析和独立样本的双因素方差分析）、相关、回归分析、卡方检验和符号检验等。

本课程是心理统计学的入门课程，授课对象为高年级本科生和硕士研究生一年级学生。本课程授课内容包括统计学简介、频率分布、集中量数、变异量数、正态分布和z分数、概率、样本和概率、假设检验、t检验（t检验简介、独立样本t检验和相关样本t检验）、方差分析（方差分析简介、重复测量的方差分析和独立样本的双因素方差分析）、相关、回归分析、卡方检验和符号检验等。本人在下学期还会专门给研究生开设一门叫做《[R语言与统计建模和数据可视化](/en/teach/R-for-Statistics-Data-Visualization/)》的统计课程。有兴趣在下学期选修该高级统计课程，但本科阶段没有学过统计学的研究生同学，应该先选修本心理统计学入门课程。
-->

# 3. Textbook

- Gravetter, F. J., & Wallnau, L. B. (2017). *[Statistics for the Behavioral Sciences](https://www.amazon.com/Statistics-Behavioral-Sciences-MindTap-Psychology/dp/1305504917)* (10 ed.): Wadsworth Publishing.

# 4. Syllabus and Lecture Notes

- Part I. Introduction and Descriptive Statistics
  - Chapter 01. Introduction to Statistics [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/StatBehavSci/CH.01.pdf)
  - Chapter 02. Frequency Distributions [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/StatBehavSci/CH.02.pdf)
  - Chapter 03. Central Tendency [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/StatBehavSci/CH.03.pdf)
  - Chapter 04. Variability [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/StatBehavSci/CH.04.pdf)


- Part II. Foundations of Inferential Statistics
  - Chapter 05. z-Scores: Location of Scores and Standardized Distributions [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/StatBehavSci/CH.05.pdf)
  - Chapter 06. Probability [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/StatBehavSci/CH.06.pdf)
  - Chapter 07. Probability and Samples: The Distribution of Sample Means [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/StatBehavSci/CH.07.pdf)
  - Chapter 08. Introduction to Hypothesis Testing [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/StatBehavSci/CH.08.pdf)

- Part III. Using *t*-Statistics for Inferences
  - Chapter 09. Introduction to the *t* Statistic  [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/StatBehavSci/CH.09.pdf)
  - Chapter 10. The *t* Test for Two Independent Samples [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/StatBehavSci/CH.10.pdf)
  - Chapter 11. The *t* Test for Two Related Samples  [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/StatBehavSci/CH.11.pdf)

- Part IV. Analysis of Variance
  - Chapter 12. Introduction to Analysis of Variance.  [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/StatBehavSci/CH.12.pdf)
  - Chapter 13. Repeated-Measures Analysis of Variance.
  - Chapter 14. Two-Factor Analysis of Variance (Independent Measures).

- Part V. Correlations and Nonparametric Tests
  - Chapter 15. Correlation.
  - Chapter 16. Introduction to Regression.
  - Chapter 17. The Chi-Square Statistic: Tests for Goodness of Fit and Independence
  - Chapter 18. The Binomial Test

# 5. Examination

- To Be Announced
<!--
- Time and location: **08:00-09:50, July 13**, **Room 104, Teaching Building 4**;
- Structure of the exam: 65 multiple choices, selected from the *learning check* problems of chapters *1 - 13*; 2 essay questions, selected from the *odd-numbered problems* of chapters *9 - 13*.
-->