---
title: 'Science and Scientific Research'
author: "Likan Zhan"
date: "2017-03-01"
#lastmod: "2021-03-02"
lastmod: "`r Sys.Date()`"
show_toc: yes
disable_comments: no
output:
  blogdown::html_page:
    toc: yes
---
# 1. Lecture Time and Location

- Time: 14:00 - 16:00 (Odd week) / 18:00 (Even week), Tuesday
- Location: 507, Teaching Building 1
- Lecturer: Likan Zhan

# 2. Course Information

This course is designed to expose students to the academic side of scientific research. They will learn the basic concepts of science and scientific research. They will also learn how to synthesize results, present them, and explore related topics. Students will analyze and discuss published research articles, engage in conversations with the teacher about different aspects of research, and design and present their own research.

# 3. Text Books

- American psychological association. (2010). *Publication manual of the American Psychological Association* (6 ed.). Washington, DC: American psychological association.
- Stanovich, K. E. (2013). *How to think straight about psychology* (10 ed.). Boston, MA: Pearson Education.

# 4. Syllabus and Lecture Notes

- Part I. Science and Scientific Research
    - 01. What is science [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](https://likan.oss-cn-beijing.aliyuncs.com/SciRec/CH-1-01.pdf)
    - 02. Falsifiability [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](https://likan.oss-cn-beijing.aliyuncs.com/SciRec/CH-1-02.pdf)
    - 03. Operationism and essentialism [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](https://likan.oss-cn-beijing.aliyuncs.com/SciRec/CH-1-03.pdf)
    - 04. Testimonials and case study [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://likan.oss-cn-beijing.aliyuncs.com/SciRec/CH-1-04.pdf)
    - 05. Correlation and causation [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://likan.oss-cn-beijing.aliyuncs.com/SciRec/CH-1-05.pdf)
    - 06. Getting things under control [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://likan.oss-cn-beijing.aliyuncs.com/SciRec/CH-1-06.pdf)
    - 07. The artificality criticism [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://likan.oss-cn-beijing.aliyuncs.com/SciRec/CH-1-07.pdf)
    - 08. The importance of converging evidence [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://likan.oss-cn-beijing.aliyuncs.com/SciRec/CH-1-08.pdf)
    - 09. The issue of multiple causation [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://likan.oss-cn-beijing.aliyuncs.com/SciRec/CH-1-09.pdf)
    - 10. Probablistic reasoning [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://likan.oss-cn-beijing.aliyuncs.com/SciRec/CH-1-10.pdf)
    - 11. The role of chance [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://likan.oss-cn-beijing.aliyuncs.com/SciRec/CH-1-11.pdf)

- Part II. Academic reading
    - 12. Category and structure of academic articles  [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://likan.oss-cn-beijing.aliyuncs.com/SciRec/CH-2-1.pdf)
    - 13. References in academic articles  [<i class="far fa-file-pdf"> \faFilePdf[regular] </i>](https://likan.oss-cn-beijing.aliyuncs.com/SciRec/CH-2-2.pdf)

<!--
    - 14. Databases, journals, and search engines
    - 15. Bibliography softwares

- Part III. Academic writing
    - 16. Good writing
    - 17. Window onto the worold
    - 18. Curse of knowledge
    - 19. Web, tree, and string
    - 20. Arcs of coherence

- Part II. Remaining problems in scientific practice
           ^[Further reading: Chambers, C. (2017).]
    - 12. Bias
    - 13. Hidden flexibility
    - 14. Unreliability
    - 15. Data horarding
    - 16. Corruptibility
    - 17. Internment
    - 18. Redemption
-->

# 4. Final examination

To Be Announced

<!--
  - Download the exam file from the following link during **2020-06-17, 1000** to **2020-06-17, 1200**.
  - Write your answers in **Mandarin CHINESE**.
  - Include your name, your student ID, name of the course in your answer sheet.
  - Rename your answer sheet with the following pattern `ID-Name`.
  - Save your answer sheet both in **.doc / .docx** format and in  **.PDF** format.
  - Send the two files to the following email address: `zhanlikan@blcu.edu.cn` before **2020-06-17, 1201**.

- Oral presentations
    - Presentation Lists: [Link](http://appendix.likan.info/Science-and-Scientific-Research/reading-lists/Presentation_Lists.xlsx)

- Procedure of Scientific Research
    - Chambers, C. (2017). *The seven deadly sins of psychology: A manifesto for reforming the culture of scientific practice*. Princeton, NJ: Princeton University Press.
    - Evans, J. S. B. T. (2016). *How to Be a Researcher: A strategic guide for academic success*. East Sussex, FA: Routledge.
    - Leek, J. (2016). *How to be a modern scientist*: Leanpub.
    - Stanovich, K. E. (2013). *How to think straight about psychology* (10 ed.). Boston, MA: Pearson Education.

- Academic writing
    - Pinker, S. (2014). *The Sense of Style: The Thinking Person's Guide to Writing in the 21st Century*. New York, NY: Penguin.

- Writing Style of American Psychological Association
    - American psychological association. (2010). *Publication manual of the American Psychological Association* (6 ed.). Washington, DC: American psychological association.
    - Nicol, A. A. M., & Pexman, P. M. (2010). *Displaying your findings: A practical guide for creating figures, posters, and presentations*. Washinton, DC: American Psychological Association.
    - Perrin, R. (2012). *Pocket Guide to APA Style*: Cengage Learning.

- Other References
    - Hock, R. R. (2009). *Forty studies that changed psychology: Explorations into the history of psychological research* (6 ed.). New Jersey, NJ: Pearson Education.
-->