---
title: R 中的 ave 函数
author: ~
date: '2018-06-15'
lastmod: "`r Sys.Date()`"
slug: 
categories: []
tags: []
---

1. `ave` 函数的论元
```{r, echo = F}
args(ave)
```
- `x`, 需要分析的数据

- `...`, 用于分组的数据，如果空缺，则把函数应用于全部数据

- `FUN`, 应用于数据 `x` 的函数。


2. 一个例子

```{r}
Score <- data.frame(
  RRR = c(2, 3,  8,  6,  5,  6),
  RPQ = c(5, 9, 10, 13,  8,  9),
  RCQ = c(8, 6, 12, 11, 11, 12)
  )
Score_long <- reshape(Score, direction = "long", 
  varying = list(names(Score)[1:3]), 
  timevar = "Condition", times = colnames(Score), v.names = "Score")
Score_long <- Score_long[, names(Score_long) != "id"]
row.names(Score_long) <- NULL
Score_long $ Group_Mean <- ave(Score_long $ Score, Score_long $ Condition)
Score_long $ Grand_Mean <- ave(Score_long $ Score)
Score_long
SS_within <- sum((Score_long $ Score - Score_long $ Group_Mean) ^ 2)
SS_between <- sum((Score_long $ Group_Mean - Score_long $ Grand_Mean) ^ 2)
SS_total <- sum((Score_long $ Score - Score_long $ Grand_Mean) ^ 2)
c(SS_total, SS_between, SS_within)
```

2. `ave` 函数的源代码
```{r, echo = F}
ave
```

2. `ave` 函数的说明文档
```{r, echo = F}
acqr::print_help_console(ave)
```
