---
title: R 中几个跟 file 有关的函数
author: ~
date: '2018-06-30'
slug: file-functions
categories: []
tags: []
---


1. 函数 'file.exists()' 文档是否存在。例如，当前工作区中不存在一个名称为 'example1.txt' 和名称为 'example2.txt' 的纯文本文档，所以输出的结果应该为 'FALSE'。

```{r, results = "hold"}
file.exists("example1.txt")
file.exists("example2.txt")
``` 

2. 我们可以用 'file.create()' 来创建一个名叫 'example1.txt' 和一个叫做  'example2.txt' 的纯文本文档。此时再运行 'file.exists()' 命令，得到的结果就是 'TRUE' 了。

```{r, results = "hold"}
invisible(file.create("example1.txt"))
invisible(file.create("example2.txt"))
file.exists("example1.txt")
file.exists("example2.txt")
``` 

3. 接下来我们可以用 'list.files()' 来查看当前目录下的文档列表

```{r, results = "hold"}
list.files(all.files = TRUE, pattern = "example*") ## all.files = TRUE 说明把隐藏文件也显示出来
```

4.接下来我们可以用 'cat()' 函数在这两个纯文本文档中添加一些信息。

```{r, results = "hold"}
cat("file A\n XX 100", file = "example1.txt")
cat("file B\n YY 200", file = "example2.txt")
# file.show("example1.txt") # 在交互运行的模式下，这个文件会被打开。
``` 

5. 我们还可以用 'file.rename()' 对文件名称进行重新命名

```{r, results = "hold"}
# file.rename(list.files(pattern = "example_*.img"), paste0("Ex_", 1:700))
``` 

6. 最后，我们可以用 'file.remove()' 删除刚才创建的两个纯文本文档

```{r, results. = "hold"}
invisible(file.remove("example1.txt"))
invisible(file.remove("example2.txt"))
```

