---
title: 论文写作中如何取悦读者、主编、和自己 ？
subtitle: 来自小说家和普利策奖获得者科马克·麦卡锡 (Cormac McCarthy) 的建议
author: ~
date: '2019-09-27'
slug: novelist-cormac-mccarthy-s-tips-on-how-to-write-a-great-science-paper
categories: []
tags: []
---

1. 用最简单的方法达成简洁性。学术论文也要在说一个自成一体的、有说服力的故事，这其中最重要的一点是要保持简洁性。写作时要这样问自己：删除那个标点、单词、句子、或章节后，文章还能保留我想表达的意思吗？竭尽所能删除额外的单词或标点符号。

2. 给文章确定一个主题和两到三个你希望每个读者都记住的要点。这个主题和两三个要点将成为贯穿整个行文的线头。而文章中的单词、句子、段落和章节将是把这些线头牵到一起的编织过程。如果某些内容无助于读者理解文章主题，那么删掉它。

3. 一个段落只关注一个信息，所以一句话可以成为一个段落。为了探索这一信息，段落应该始于一个问题，然后通达一个想法或一个答案。当然只提问题，不供答案也是完全可行的。

4. 保持句子长度短、结构简单和直接。对学术论文而言，句子简洁、清楚就够了。尽量少用从句、复句和连接词，如 'however'， 'thus' 等，以帮助读者把注意集中在文章要表达的信息上。

5. 不要拖慢读者的阅读进程。减少使用脚注。脚注带来的来回翻页或链接点击会中断读者的想法。避免使用专有名词、时髦词、或过于技术的语言。不要重复使用同一个词 - 这样很无聊。

6. 描述不要过于详尽。如无必要不使用形容词。文章并不是与读者的潜在问题进行对话，所以不用热衷于预测它们。在一个地方中没有必要用三种方式表达同一件事情。没必要同时用 'elucidate' 和 'elaborate'，选一个就行了，否则你可能会吓跑读者。

7. 不用因为过于担心读者会找到某个点反驳文章中的观点，从而列出每个命题的所有证据。享受写作过程就好了。

8. 文章第一稿最好的语法指导是口语和常识。学术论文写作中，写一篇可懂度高的文章，比写一系列语法上完美的句子更重要。

9. 逗号和语言中的停顿。句首短语 ‘in contrast' 需要一个逗号来强调当前句子和前面句子的不同，而不是句首两个词和其他词的不同。把句子出声读出来，以找到句子的停顿位置。

10. 破折号的作用不仅仅是定义某些术语，更应该被用来强调最重要的句子 - 不通过使用加粗和斜体。（括号能比逗号更安静和更优雅的展示句子）。不要依仗分号把联系不紧密的想法弄成一个整体，这只会让写作更糟糕。不用过于正式，缩略形式偶尔也可以使用，如isn't don't, it's 和 shouldn't等。不要通过喊叫强调观点的重要性。可以用 'suprisingly' 或 ‘intriguingly' 但不易滥用。一篇文章用一两次就够了。

11. 插入疑问句和一些非正式表达以增强文章趣味性和阅读友好性。口语化表达是一个选择，但是选择的口语不应该过于具有地域特异性。类似的，个人化表达也是一个选择，因为它能让阅读过程更有趣。表达方式的非个人化并不表示其表达思想的客观性，例如 '地球是这个太阳系的中心' 并不比 '我们是我们太阳系的中心 更客观。

12. 选择具体的语言和例子。如果你要讨论一个可以有任意颜色的抽象球体，把这个物体描述为红色的气球或蓝色的台球更具吸引力。

13. 不要把公式放在句子当中。数学不同于英语，我们也不应该假装它们是相同的。为了把等式和文字分开，你可以用换行、空格、附录章节、符合直觉的符号和清楚的解释等，宜告诉读者怎样在假设和公式之间进行转换。

14. 写完之后，把文章读给你自己或你朋友听。找一个你信任并能真的花时间和精力的人帮你阅读。尽量让朋友的阅读过程更舒适，例如给文章添加页码、双倍行距等。

15. 最后，把你的文章寄给杂志主编。在评审和主编的评审意见回来之前不用再去思考这篇文章。当评审意见返回时，记住 Rudyard Kipling 的话 _当所有人都怀疑你时，你要相信自己，但你也要要允许他们进行怀疑_。有用的建议，按建议修改；无用的建议，策略性的回复，解释为什么你要保持原来的说法。

16. 不要因为所谓的剑桥逗号、'significantly' 等正确用法，或 'that' 与 'which' 的正确选择与主编争论。每个杂志自己的行文规则。你也不例外。

17. 最后，你的文章要是最好的版本：即你喜欢的那一版本。你也许无法让匿名的读者满意，但是你应该让自己满意。你的论文是为后世服务的。当你享受自己的写作过程时，要记住你第一次阅读时他人的文章是怎样吸引你的。


参考文献

- Savage, V., & Yeh, P. (2019). Novelist Cormac McCarthy’s tips on how to write a great science paper. *Nature*. doi:10.1038/d41586-019-02918-5

