---
title: "Teaching Responsibilities"
author: "Likan Zhan"
date: '2017-03-08'
disable_comments: true
---

### Semester one (September - January)

- [Statistics for the Behavioral Sciences](/en/teach/Statistics-for-the-Behavioral-Sciences/) <br>
    Targeted Students: Undergraduate students

- [Introduction to Cognitive Neuroscience](/en/teach/Introduction-to-Cognitive-Neuroscience/) <br>
    Targeted Students: Postgraduate and PhD students

- [Data Science with Julia](https://statisticswithjulia.likan.info)<br>
    Targeted Students: Postgraduate and PhD students

### Semester two (March - July)

- [Experimental Psychology](/en/teach/Experimental-Psychology/) <br>
    Targeted Students: Undergraduate students

- [Science and Scientific Research](/en/teach/Science-and-Scientific-Research/) <br>
    Targeted Students: Undergraduate students

- [Introduction to Neurolinguistics](/en/teach/Introduction-to-Neurolinguistics/) <br>
    Targeted Students: Undergraduate Students

### Archived Courses

- [R for Statistics and Data Visualization](/en/teach/R-for-Statistics-Data-Visualization/) <br>
    Targeted Students: Postgraduate and PhD students <br>
    This course is archived, please refer to the new course [Data Science with Julia](https://statisticswithjulia.likan.info)

- [Applied Statistics](/en/teach/Applied-Statistics/) <br>
    Targeted Students: Undergraduate students <br>
    This course is archived, please refer to the course [Statistics for the Behavioral Sciences](/en/teach/Statistics-for-the-Behavioral-Sciences/)

