---
title: "Chapter 4. Variability"
author: "Likan Zhan"
date: '2017-03-27'
output:
  blogdown::html_page:
    toc: true
    fig_width: 12
    fig_height: 8
---

# Figure 4.3

```{r label = "Figure_04_03", echo = TRUE, eval = TRUE, results = "asis"}
X <- c(1, 9, 5, 8, 7)
hist(X,
     breaks = seq(0.5, 10.5, by = 1),
     ylim = c(0, 3),
     xlim=c(0, 11),
     yaxs="i",
     xaxs="i",
     col = "#f8cea2",
     border = "#b78135",
     axes = FALSE,
     main = "",
     font.lab = 2
)
axis(1,
    at = -1:10,
    label = -1:10
)
axis(2,
    at = 0:3,
    label = 0:3
)
segments(
    c(1, 7),
    c(1,1),
    c(1, 7),
    c(2.5, 2.5),
    col = "#cf232a",
    lty = 2,
    lwd = 2
)
abline(v = 6,
      col = "#cf232a",
      lwd = 2
)
arrows(
      c(3.3, 3.7, 6.3, 6.7),
      c(2.5, 2.5, 2.5, 2.5),
      c(1, 6, 6, 7),
      c(2.5, 2.5, 2.5, 2.5),
      col = "#cf232a",
      lwd = 2,
      length = 0.1
)
text(c(3.5, 6.5),
     c(2.5, 2.5),
     c("5", "1")
)
mtext(expression(paste(mu, " = 6", sep = "")),
      side = 3,
      adj = 0.55
)
```

# Figure 4.5

```{r label = "Figure_04_05", echo = TRUE, eval = TRUE, results = "asis"}
X <- c(4, 6, 5, 11, 7, 9, 7, 3)
hist(X,
     breaks = seq(0.5, 11.5, by = 1),
     ylim = c(0, 3),
     xlim = c(0.5, 12.5),
     yaxs = "i",
     xaxs = "i",
     col = "#f8cea2",
     border = "#b78135",
     axes = FALSE,
     main = "",
     font.lab = 2
)
axis(1,
    at = 0:12,
    label = 0:12
)
axis(2,
    at = 0:3,
    label = 0:3
)
segments(
    c(6, 11),
    c(1, 1),
    c(6, 11),
    c(2.5, 2.5),
    col = "#cf232a",
    lty = 2,
    lwd = 2
)
abline(v = 6.5,
      col = "#cf232a",
      lwd = 2
)
arrows(
      c(8.7, 9.3, 6.25, 6.25),
      c(2.5, 2.5, 2.5, 2.5),
      c(6,   11 , 6, 6.5),
      c(2.5, 2.5, 2.5, 2.5),
      col = "#cf232a",
      lwd = 2,
      length = 0.1
)
text(c(9  , 6.2),
     c(2.5, 2.6),
     c("4.5", "0.5")
)
mtext("M = 6.5",
      side = 3,
      adj = 0.5
)
```

# Figure 4.7

```{r label = "Figure_04_07", echo = TRUE, eval = TRUE, results = "asis"}
X <- c(28, 31, 31 , 33, 33, 34, rep(35, 3),
       rep(36, 3), 37, 37, 38, 38, 39, 40, 43, 45
)
hist(X,
     breaks = seq(27.5, 46.5, by = 1),
     ylim = c(0, 4),
     xlim = c(27, 47),
     yaxs = "i",
     xaxs = "i",
     col = "#f8cea2",
     border = "#b98438",
     axes = FALSE,
     main = "",
     font.lab = 2
)
axis(1,
    at = seq(26, 46.5, by = 2),
    label = seq(26, 46.5, by = 2)
)
axis(2,
    at = 0:3,
    label = 0:3
)
segments(
    c(30.5, 32.5, 34.5),
    c(1,    1,    2   ),
    c(31.5, 40.5, 38.5),
    c(1,    1,    2   ),
    col = "#b98438"
)

segments(
    c(32, 36, 40),
    c(-1, 3,  1),
    c(32, 36, 40),
    c(3.7,  4,  3.7),
    lty = c(2, 1, 2),
    col = "#cf232a",
    lwd = 1.5
)
arrows(
      c(36,  36),
      c(3.5, 3.5),
      c(32,  40),
      c(3.5, 3.5),
      col = "#cf232a",
      lwd = 1.5,
      length = 0.1
)
text(c(34, 38),
     c(3.6, 3.6),
     c("s = 4", "s = 4")
)
mtext("M = 36",
      side = 3,
      adj = 0.45
)
```



# Figure.4.8

- Figure 4.8.a

```{r label = "Figure_04_08_a", echo = TRUE, eval = TRUE, results = "asis"}
ExA <- data.frame(
       Treatment_1 = c(35, 34, 36, 35),
       Treatment_2 = c(39, 40, 41, 40)
)
hist(ExA[, "Treatment_1"],
     breaks = seq(31.5, 42.5, by = 1),
     ylim = c(0, 2.7),
     xlim = c(32, 42),
     yaxs = "i",
     xaxs = "i",
     col = "#fce2b7",
     border = "#b98438",
     axes = FALSE,
     main = "",
     font.lab = 2,
     xlab = "X"
)
axis(1,
    at = seq(32, 42, by = 1),
    label = c(0, seq(33, 42, by = 1))
)
axis(2,
    at = 0:3,
    label = 0:3
)
library(plotrix)
axis.break(1,
     breakpos =  32.5,
     style = "zigzag",
     brw = 0.05
)
text(x = 35,
     y = 2.5,
     label = "Treatment 1: M = 35"
)
hist(ExA[, "Treatment_2"],
     breaks = seq(34.5, 42.5, by = 1),
     ylim = c(0, 2.7),
     xlim = c(32, 42),
     yaxs = "i",
     xaxs = "i",
     col = "#a0d5cf",
     border = "#009f9b",
     axes = FALSE,
     main = "",
     font.lab = 2,
     add = TRUE
)
segments(
    c(33.5, 38.5),
    c(1,    1   ),
    c(36.5, 41.5),
    c(1,    1   ),
    col =
    c("#b98438", "#009f9b")
)

text(x = 40,
     y = 2.5,
     label = "Treatment 2: M = 40"
)
```


- Figure 4.8.b

```{r label = "Figure_04_08_b", echo = TRUE, eval = TRUE, results = "asis"}
ExB <- data.frame(
       Treatment_1 = c(31, 15, 57, 37),
       Treatment_2 = c(46, 21, 61, 32)
)
hist(ExB[, "Treatment_1"],
     breaks = seq(10.5, 62.5, by = 1),
     ylim = c(0, 1.5),
     xlim = c(10, 63),
     yaxs = "i",
     xaxs = "i",
     col = "#fce2b7",
     border = "#b98438",
     axes = FALSE,
     main = "",
     font.lab = 2,
     xlab = "X"
)
axis(1,
    at = seq(10, 70, by = 10),
    label = seq(10, 70, by = 10)
)
axis(2,
    at = 0:3,
    label = 0:3
)

hist(ExB[, "Treatment_2"],
     breaks = seq(10.5, 62.5, by = 1),
     ylim = c(0, 1.5),
     xlim = c(10, 63),
     yaxs = "i",
     xaxs = "i",
     col = "#a0d5cf",
     border = "#009f9b",
     axes = FALSE,
     main = "",
     font.lab = 2,
     add = TRUE
)
text(x = 20,
     y = 1.3,
     label = "Treatment 1: M = 35"
)

text(x = 50,
     y = 1.3,
     label = "Treatment 2: M = 40"
)
```
