---
title: "Chapter 5. z-Scores"
author: "Likan Zhan"
date: '2017-05-03'
output:
  blogdown::html_page:
    number_sections: true
    toc: true
    fig_width: 12
    fig_height: 8
---

# Figure.05.02

```{r label = "Figure_05_02", echo = TRUE, eval = TRUE}
X <- function(mean, sd) {
     X <- seq((mean - 3 * sd),
              (mean + 3 * sd),
              by = 0.01
             )
     return(X)
}

Y <- function (mean, sd, ...) {
	  dots <- list(...)
	  if (length(dots) == 0)
	     X <- X(mean, sd)
	  else
	    X <- unlist(dots)
      Y <- dnorm(X,
                mean = mean,
                sd = sd
           )
      return(Y)
}

pp <- function(mean, sd){
plot(X(mean, sd),
     Y(mean, sd),
     type = "l",
     xlab = "",
     ylab = "",
     axes = FALSE,
     col = "#af1e23",
     lwd = 2
)
abline(h = 0)
segments(
     c(mean, mean + sd),
     c(0, 0),
     c(mean, mean + sd),
     c(Y(mean, sd, mean),
       Y(mean, sd, mean + sd)
      ),
      lty = c(1, 2)
)
arrows(
      mean,
      Y(mean, sd, mean + sd),
      mean + sd,
      Y(mean, sd, mean + sd),
      length = 0.08
)
text(
    x = mean + sd / 2,
    y = Y(mean, sd, mean + sd),
    pos = 3,
    label = bquote(sigma == .(sd)),
)
mtext(c(mean, mean + sd),
      side = c(1, 1),
      adj = c(3, 4) / 6,
      padj = - 0.7
)
mtext("X = 76",
      side = 1,
      adj = (3 + 6 / sd ) /6,
      padj = 2
)
arrows(76,
      -Y(mean, sd, mean + sd) / 6,
      76,
      0,
      xpd = TRUE,
      length = 0.08
)
}
par(mfrow = c(1, 2))
pp(70, 3)
pp(70, 12)
```

# Figure.05.03

```{r label = "Figure_05_03", echo = TRUE, eval = TRUE}

X <- function(mean, sd) {
     X <- seq((mean - 3 * sd),
              (mean + 3 * sd),
              by = 0.01
             )
     return(X)
}

Y <- function (mean, sd, ...) {
	  dots <- list(...)
	  if (length(dots) == 0)
	     X <- X(mean, sd)
	  else
	    X <- unlist(dots)
      Y <- dnorm(X,
                mean = mean,
                sd = sd
           )
      return(Y)
}

pp <- function(mean, sd){
plot(X(mean, sd),
     Y(mean, sd),
     xlim = c(mean - 4 * sd,
              mean + 4 * sd),
     type = "l",
     xlab = "",
     ylab = "",
     axes = FALSE,
     col = "#af1e23",
     lwd = 2
)
axis(
    1,
    at = seq(mean -  3 * sd,
             mean + 3 * sd,
             by = sd
             ),
    labels = FALSE,
    line = 0,
)
axis(
    1,
    at = seq(mean -  3 * sd,
             mean + 3 * sd,
             by = sd
            ),
    labels = seq(-3, 3, by = 1),
    line = 2
)
mtext(expression(mu),
      1,
      padj = 1)
mtext(text = c("X", "z"),
      side = c(1, 1),
      adj = c(0.87, 0.87),
      xpd = TRUE,
      padj = c(-0.5, 2.5)
)
segments(
     x0 = c(
       mean,
       mean + sd,
       mean + 2 * sd,
       mean - sd,
       mean - 2 * sd
       ),
     y0 = 0,
     x1 = c(
       mean,
       mean + sd,
       mean + 2 * sd,
       mean - sd,
       mean - 2 * sd
       ),
     y1 = c(
       Y(mean, sd, mean),
       rep(
       Y(mean, sd, mean + sd),
       4
       )
     ),
      lty = 5
)
text(
    x = mean + sd / 2,
    y = Y(mean, sd, mean + sd),
    pos = 3,
    label = bquote(sigma),
)
arrows(
      x0 = c(
        mean,
        mean,
        mean + sd,
        mean - sd
      ),
      y0 = Y(mean, sd, mean + sd),
      x1 = c(
        mean + sd,
        mean - sd,
        mean + 2 * sd,
        mean - 2 * sd
      ),
      y1 = Y(mean, sd, mean + sd),
      length = 0.08
)
}
pp(70, 3)
```

# Figure.05.04

```{r label = "Figure_05_04", echo = TRUE, eval = TRUE}
X <- function(mean, sd) {
     X <- seq((mean - 3 * sd),
              (mean + 3 * sd),
              by = 0.01
             )
     return(X)
}

Y <- function (mean, sd, ...) {
	  dots <- list(...)
	  if (length(dots) == 0)
	     X <- X(mean, sd)
	  else
	    X <- unlist(dots)
      Y <- dnorm(X,
                mean = mean,
                sd = sd
           )
      return(Y)
}

pp <- function(mean, sd){
plot(X(mean, sd),
     Y(mean, sd),
     xlim = c(mean - 4 * sd,
              mean + 4 * sd),
     type = "l",
     xlab = "",
     ylab = "",
     axes = FALSE,
     col = "#af1e23",
     lwd = 3
)
axis(
    1,
    at = seq(mean -  3 * sd,
             mean + 3 * sd,
             by = sd
             ),
    labels = FALSE,
    line = 0,
)
mtext(text = c(
        bquote(.(mean)),
        bquote(.(mean - 2 * sd))
        ),
      side = 1,
      padj = 1,
      adj = c(3, 3 - 1.45) / 6
      )
mtext(text = "X",
      side = 1,
      adj = 0.87,
      xpd = TRUE,
      padj =-0.5
)
segments(
     x0 = c(
       mean,
       mean - sd,
       mean - 2 * sd
       ),
     y0 = 0,
     x1 = c(
       mean,
       mean - sd,
       mean - 2 * sd
       ),
     y1 = c(
       Y(mean, sd, mean),
       rep(
       Y(mean, sd, mean + sd),
       2
       )
     ),
      lty = c(1, 5, 5)
)
text(
    x = c(
     mean - sd / 2,
     mean - 1.5 * sd
    ),
    y = Y(mean, sd, mean + sd),
    pos = 3,
    label = bquote(sigma),
)
arrows(
      x0 = c(
        mean,
        mean - sd
      ),
      y0 = Y(mean, sd, mean + sd),
      x1 = c(
        mean - sd,
        mean - 2 * sd
      ),
      y1 = Y(mean, sd, mean + sd),
      length = 0.08
)
segments(x0 = c(mean - 2 * sd,
                mean,
                mean - 2 * sd
         ),
         y0 = c(
              -Y(65, 3, 65)/5,
              -Y(65, 3, 65)/4,
              -Y(65, 3, 65)/4
         ),
         x1 = c(mean,
                mean,
                mean - 2 * sd
         ),
         y1 = c(
                -Y(65, 3, 65)/5,
                -Y(65, 3, 65)/7.5,
                -Y(65, 3, 65)/7.5
         ),
         xpd = TRUE
)
mtext(
      text = "6 points",
      side = 1,
      adj = 2.3/6,
      padj = 4,
)
}
pp(65, 3)
```

# Centering and scale
```{r}
X <- c(0, 2, 4, 4, 5)
SS <- sum(X^2) - (sum(X))^2 / length(X)
s <- sqrt(SS / (length(X) - 1))
M <- mean(X)
z <- (X - M) / s
print(z)

scale(X)
```
