---
title: Useful links
author: "Likan Zhan"
date: '2019-11-02'
lastmod: "`r Sys.Date()`"
output:
  blogdown::html_page:
    toc: true
---

# Experiment design

- [jsPsych](https://www.jspsych.org): A JavaScript library for creating and running behavioral experiments in a web browser.
- [PsychoPy](http://psychopy.org): PsychoPy is a free cross-platform package allowing you to run a wide range of experiments in the behavioral sciences (neuroscience, psychology, psychophysics, linguistics...)

# Research groups and personal websites

1. Language

- [Barr, Dale](https://www.gla.ac.uk/researchinstitutes/neurosciencepsychology/staff/dalebarr/), University of Glasgow, UK
- [Fitch, Tecumseh](https://homepage.univie.ac.at/tecumseh.fitch/), University of Vienna, Austria.
- [Huang, Yi Ting](https://hesp.umd.edu/facultyprofile/huang/yi-ting), University of Maryland, MD.
- [Huettig, Falk](https://www.mpi.nl/people/huettig-falk), MPI for Psycholinguistics, the Netherlands.
- [Johnson, Keith](http://linguistics.berkeley.edu/~kjohnson/index.html), University of California at Berkeley, CA.
- [Markman, Ellen M.](http://markmanlab.stanford.edu/index.html), Stanford University, CA.
- [Poeppel, David](http://as.nyu.edu/content/nyu-as/as/faculty/david-poeppel.html), New York University, NY.
- [Traxler, Matthew](https://psychology.ucdavis.edu/people/traxler), University of California at Davis, CA
- [Trueswell, John](http://web.sas.upenn.edu/trueswell-lab/people/trueswell/), University of Pennsylvania, PA.
- [Ullman, Michael](https://georgetown.app.box.com/s/5lrbyhfe5iq07xim1b13t15tjx7m9hyl), Georgetown University, Washington, D.C.
- [Xu, Yi](http://www.homepages.ucl.ac.uk/~uclyyix/), University College London, UK.

2. Social Cognition

- [Frith, Uta](https://sites.google.com/site/utafrith/), University College London, UK.
- [Heyes, Cecilia](http://users.ox.ac.uk/~ascch/index.htm), University of Oxford, UK.
- [Sloman, Steven](https://sites.google.com/site/slomanlab/lab-members), Brown University.
- [Wang, Zheng](https://www.thedocc.com), The Ohio State University, OH.
- [Jerome R. Busemeyer](https://jbusemey.pages.iu.edu/home.html) and his [Judgment and Decision Research Lab](https://jbusemey.pages.iu.edu/lab/Lab.htm), Indiana University.

3. Reasoning

- [Shira Elqayam](https://www.dmu.ac.uk/about-dmu/academic-staff/health-and-life-sciences/shira-elqayam/shira-elqayam.aspx), De Montfort University, UK

# Free online books for Julia and Statistics

- [Introduction to Applied Linear Algebra](https://web.stanford.edu/~boyd/vmls/) – Vectors, Matrices, and Least Squares
- [Statistics with Julia](https://statisticswithjulia.org/index.html): Fundamentals for Data Science, Machine Learning and Artificial Intelligence
- [Statistical Rethinking](https://xcelab.net/rm/statistical-rethinking/): A Bayesian Course with Examples in R and Stan

# Graphical statistical tools based on R

- [JASP](https://github.com/jasp-stats/jasp-desktop): JASP is an open-source statistics program that is free, friendly, and flexible. Armed with an easy-to-use GUI, JASP allows both classical and Bayesian analyses.
- [jamovi](https://www.jamovi.org/): jamovi is a new “3rd generation” statistical spreadsheet.
- [The R Commander](https://socialsciences.mcmaster.ca/jfox/Misc/Rcmdr/index.html): The R Commander is a graphical user interface (GUI) to the free, open-source R statistical software. The R Commander is implemented as an R package, the Rcmdr package, which is freely available on CRAN (the R package archive).

# Un-categorized useful links

- [ThreeDWorld](http://www.threedworld.org): A High-Fidelity, Multi-Modal Platform for Interactive Physical Simulation
- [International Picture Naming Project website](https://crl.ucsd.edu/experiments/ipnp/1stimuli.html): The picture stimuli set consist of black-and-white line drawings of 520 common objects and 275 transitive and intransitive actions.
- [De-Jargonizer](http://scienceandpublic.com/): An online tool that assesses and scores the accessibility of text.
- [Critical Analysis Project](http://critical-analysis.org/)
- [THINGS object concept and object image database](https://osf.io/jum2f/)
- [Biological Motion Lab](https://www.biomotionlab.ca)
- [Advent of Code](https://adventofcode.com)