---
title: "Experimental Psychology"
author: "Likan Zhan"
date: '2017-03-01'
#lastmod: "`2021-03-16"
lastmod: "`r Sys.Date()`"
show_toc: yes
disable_comments: no
output:
  blogdown::html_page:
    toc: yes
---

# 1. Time and Location

- Time: 08:00 - 12:00, Wednesday
- Location: 203, Main Building South
- Lecturer: Likan Zhan

# 2. Course Information

Experimental psychology is part of the very core of the discipline of psychology. Whether your interest is in learning about animal or human behavior, pure theoretical questions or applied problems, research or practice with children or adults, you cannot correctly understand your material, investigate your questions, or apply your knowledge without a clear understanding and ability to use the principles and methods of experimental psychology. 

Therefore, this course should help you:

  a. Understand the rationale, strengths and limitations of the experimental method of gaining knowledge about mental and behavioral processes.
  b. Learn how to design experimental and non-experimental studies.
  c. Know how to use the various methods used in experimental psychology, including those for humans, both self-report and non self-report based.

# 3. Text Books

- Kantowitz, B. H., Roediger, H. L., III, & Elmes, D. G. (2015). *Experimental Psychology* (10 ed.). Cengage Learning.
- Shaughnessy, J. J., Zechmeister, E. B., & Zechmeister, J. S. (2012). *Research methods in psychology* (9 ed.). McGraw-Hill.

# 4. Syllabus and Lecture Notes

- Part I. Foundations of Research
    - Chapter 01. Explanation in Scientific Psychology [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/ExpPsychol/CH-01.pdf)
    - Chapter 02. Descriptive Methods [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/ExpPsychol/CH-02.pdf)
    - Chapter 03. Experimental Methods [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/ExpPsychol/CH-03.pdf)
    - Chapter 04. Applied Research [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/ExpPsychol/CH-04.pdf)
    - Chapter 05. Ethics in Psychological Research

- Part II. Principles and Practices of Experimental Psychology 
    - Chapter 06. Psychophysics [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/ExpPsychol/CH-06.pdf)
    - Chapter 07. Perception [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/ExpPsychol/CH-07.pdf)
    - Chapter 08. Attention and Reaction Time [<i class="far fa-file-pdf">\faFilePdf[regular]</i>](http://likan.oss-cn-beijing.aliyuncs.com/ExpPsychol/CH-08.pdf)
    - Chapter 09. Conditioning and Learning
    - Chapter 10. Remembering and Forgetting
    - Chapter 11. Thinking and Problem Solving
    - Chapter 12. Individual Differences and Development
    - Chapter 13. Social Psychology
    - Chapter 14. Environmental Psychology
    - Chapter 15. Human Factors

# 6. Final Examination

To Be Announced

<!--
  - Download the exam file from the following link during **2020-06-15, 1410** to **2020-06-15, 1610**.
  - Write your answers in **Mandarin CHINESE**.
  - Include your name, your student ID, name of the course in your answer sheet.
  - Rename your answer sheet in the following pattern `ID-Name`.
  - Save your answer sheet both in **.doc / .docx** format and in  **.PDF** format.
  - Send the two files to the following email address: `zhanlikan@blcu.edu.cn` before **2020-06-15, 1611**.
-->