---
title: "期末考试试卷"
author: "李四 - 20181030"
date: '2020-12-23'
output:
  pdf_document:
    fig_height: 6
    fig_width: 6
    latex_engine: xelatex
    toc: yes
    toc_depth: 3
  word_document:
    toc: yes
    toc_depth: '3'
  html_document:
    fig_height: 6
    fig_width: 6
    toc: yes
subtitle: R语言与数据可视化和统计
header-includes: \usepackage{ctex}
---

### 1. 课程建议 (10分)
- 请给本课提一些建设性建议，以帮助任课教师在将来授课中为同学提供更好的服务。


### 2. 数据整理 (18分)
 
 - 一组数据是否整洁 (tidy的标准是什么？)

 - 请根据上述标准解释包 `tidyr` 中的数据 `table4a` 和 `table2` 是否整洁，为什么

 - 请用恰当方法对上述数据进行整理。


### 3. 数据探索 (18分)
- 包 `carData` 中有一个叫 `Leinhardt` 的数据文件。该文件为105个国家（行数）在1970年代左右的数据。该文件共有4个变量（列数）：`income` 表示该国人均收入水平；`infant` 表示该国每1000个新生儿中的儿童死亡率；`region` 表示该国所属地区；`oil` 表示该国是否为石油输出国。

- 数据中存在一些缺失值，先用合适的方法去掉缺失值。

- 请先画出变量 `infant` 和变量 `income` 的概率密度图，并分析该分布的正态性。

- 如果分布为非正态，请用学过的方法对这两列数据进行转化

- 以转化后的新生儿死亡率为纵坐标，转化后的收入水平为横坐标，做一个散点图，并添加一条蓝色的回归直线和一条红色的非参数回归线。

### 4. 线性回归 (18分)
- 包`carData`中有一个叫 `Anscombe` 的数据文件。该文件为美国51个州及华盛顿特区（行数）的公共教育支出情况。该文件共有四个变量（列数）：`education` 为该州人均教育支出量（美元）；`income` 为该州人均收入水平；`young` 为该州每1000个人中小于18岁的年轻人的数量；`urban` 为该州每1000个人中城市人口的数量。请用合适的方法选择合适的回归因子考察人均教育支出量的影响因素，并报告实验结果。

### 5. 哑变量回归 (18分)

- 回到数据文件 `Leinhardt`。请考察该国转化后的人均收入水平`income` 和该国所处的地区 `region` 对转化后的新生儿死亡率的影响，及新生儿死亡率在这两个变量上的回归，并报告实验结果。 请用亚变量回归的方法对类别型变量进行编码。

### 6. 方差分析 (18分)

- 作答要求：`carData` 包中有一个叫`Guyer`的数据文件。该文件共有20行，三个变量：`cooperation` 说的是被试的合作分数（即在120个试次中，选择合作的次数）；`condition` 说的是测试条件，即被试是否是匿名。第三个变量`sex`为性别。请分别用亚变量`dummy`和`sum-to-zero(sigma)`方法对类别变量进行编码，并用方差分析方法考察被试性别和是否匿名对被试合作分数的影响。